### ISSUE TITLE
3.7.3 regression: generated man pages not included in release tgz

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#1000]
There is a regression in the 3.7.3 release tgz: generated man pages are not included. All previous release tgz files included those.
This kind of change is unexpected for a minor release, and problematic even for major releases:
- it adds a build dependency to the package containing xsltproc (different in each distro)

and one of these:
- download manpages/docboox.xsl from the internet (which is often impossible, see OBS and most corporate environments)
- adds a build dependency to the package containing manpages/docboox.xsl (different in each distro) and add --with-docbook-dir to configure, where the exact path is different in each release

Using the following ./configure parameters before "make dist" resolves this problem and generates man pages for the dist tgz as expected:

```
 ./configure --enable-manpages
--with-docbook-dir=/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl
```

**Comment by cschuber** [comment]
This is a problem for FreeBSD package generation. The the package builders don't have direct Internet access during the body of the build process.

cy@freebsd.org

**Comment by lbudai** [comment]
@cschuber : 

We will fix the tarball, so the answers to the following questions won't affect the fact that we will re-release syslog-ng-3.7.3 with the missing xsl file. I'm just interesting in the answers.

( Currently syslog-ng release tarball does not contain manpages but only the xsl and the doc: the latest release came out without the xsl. )

* Is there a package on FreeBSD that contains the docbook.xsl?
* If there is such a package, would it be a problem to set it as a build dependency?
And in this case wouldn't be it a cleaner solution? If a distro/OS has its own docbook.xsl then maybe it is better if that file is used instead of the docbook.xsl installed on my environment.

**Comment by czanik** [comment]
Yes, there is. On the other hand if you compile syslog-ng from source (and if you need anything more than core functionality, then you need to compile), it multiples the number of build dependencies by 3x together with the required disk space.

**Comment by lbudai** [comment]
Could you list those dependencies? Maybe I miss something...

**Comment by czanik** [comment]
The dependencies of libxslt and docbook-xsl packages, all together 11 packages and over 30 megabytes for a package normally taking around 2.5 megabytes. These are just required to be able to build manual pages from the XML sources.
BTW: it's not the XSL file missing from the release tgz, but the generated man pages: currently only the xml sources are included.

**Comment by cschuber** [comment]
In message <balabit/syslog-ng/issues/1000/202827005@github.com>, Budai 
Laszlo w
rites:
> 
> ----==_mimepart_56fa5b91c43cb_68793f92261b329c387405e
> Content-Type: text/plain;
>  charset=UTF-8
> Content-Transfer-Encoding: 7bit
> 
> Could you list those dependencies? Maybe I miss something...

The FreeBSD project prefers to use dependencies rather than bloat packages 
with duplicate software. Otherwise we can bloat but with an options knob.

I've updated the port to depend on the docbook-xsl port/package.


-- 
Cheers,
Cy Schubert <Cy.Schubert@komquats.com> or <Cy.Schubert@cschubert.com>
FreeBSD UNIX:  <cy@FreeBSD.org>   Web:  http://www.FreeBSD.org

	The need of the many outweighs the greed of the few.

**Comment by Kokan** [comment]
The man page is part of the latest syslog-ng tarball, it is still missing from 3.7.3, but that is kinda old now, and I think it should not be regenerated.
