### ISSUE TITLE
xmllint is required for building syslog-ng

### ISSUE THREAD

**Issue by darxtrix** [balabit/syslog-ng#1087]
I was trying to build `syslog-ng(syslog-ng 3.8.0alpha0)` from source. I used the following dependencies:
- https://github.com/balabit/syslog-ng-docker/blob/master/syslog-ng-dev/dev-dependencies.txt
- https://github.com/balabit/syslog-ng/blob/master/.travis.yml

The build succeeds but one of the tests `modules/dbparser/tests/test_patterndb` fails. A quick look in the log file suggests `xmllint` is required for passing this test.

``` shell
FAIL: ASSERTION FAILED: Error validating patterndb, error=Failed to execute child process "xmllint" (No such file or directory)
```

I cannot see the package in the list of dependencies. So, I guess it should be added to them.

**Comment by bazsi** [comment]
You are right. It became a dependency for tests just recently. It is not
needed during production runs.

Bazsi
On Jun 13, 2016 7:25 PM, "Ankush Sharma" <notifications@github.com> wrote:

I was trying to build syslog-ng(syslog-ng 3.8.0alpha0) from source. I used
the following dependencies:

   -
   https://github.com/balabit/syslog-ng-docker/blob/master/syslog-ng-dev/dev-dependencies.txt
   - https://github.com/balabit/syslog-ng/blob/master/.travis.yml

The build succeeds but one of the tests
modules/dbparser/tests/test_patterndb fails. A quick look in the log file
suggests xmllint is required for passing this test.

FAIL: ASSERTION FAILED: Error validating patterndb, error=Failed to
execute child process "xmllint" (No such file or directory)

I cannot see the pac
I was trying to build syslog-ng from source. I used the following
dependencies:

   -
   https://github.com/balabit/syslog-ng-docker/blob/master/syslog-ng-dev/dev-dependencies.txt
   - https://github.com/balabit/syslog-ng/blob/master/.travis.yml

The build succeeds but one of the tests
modules/dbparser/tests/test_patterndb fails. A quick look in the log file
suggests xmllint is required for passing this test.

FAIL: ASSERTION FAILED: Error validating patterndb, error=Failed to
execute child process "xmllint" (No such file or directory)

I cannot see the package in the list of dependencies. So, I guess it should
be added to them.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/balabit/syslog-ng/issues/1087>, or mute the thread
<https://github.com/notifications/unsubscribe/AArldhrgVOTD_1xOyUt_tQjEc_MmJpCQks5qLZJzgaJpZM4I0jYz>
.

**Comment by bkil-syslogng** [comment]
A fix would involve detecting the presence of the package in `configure.ac` and disabling the said test based on results. A warning should also be emitted. An alternative would be to fail the test by default with a warning explaining that this package is missing and require an extra configure option to disable this test and get a green light on `make check`.

**Comment by bkil-syslogng** [comment]
Package maintainers could also consider suggesting/recommending `xmllint`

**Comment by bkil-syslogng** [comment]
We should also update the compilation guide:
https://github.com/balabit/syslog-ng-ose-guides/blob/master/en/syslog-ng-guide-admin/chapters/compiling-syslog-ng.xml

**Comment by lbudai** [comment]
@bkil-syslogng : package maintainers should not recommend `xmllint` as they only need this in their build environment.

**Comment by lbudai** [comment]
@bkil-syslogng : will you create a PR that satisfies your requirements?

**Comment by bkil-syslogng** [comment]
See `Build-Depends`

**Comment by lbudai** [comment]
@bkil-syslogng : ?

**Comment by lbudai** [comment]
@bkil-syslogng :
When someone want to use the Debian source from my repo, `apt-get build-dep` will install `xmllint` (my `Build-Depends` section contains libxml2-utils which then install `xmllint`, otherwise I wouldn't be able to build syslog-ng... so still not clear what do you want to say). 

You can check it yourself, if you have doubts:
```
wget -qO - http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_14.04/Release.key | sudo apt-key add -
```

add the followings to your apt sources list:
```
deb http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_14.04 ./
deb-src http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_14.04 ./
```

then

```
apt-get build-dep syslog-ng-core
```

**Comment by Kokan** [comment]
Since 9540c346f4d95a0d6564a21aa76a9268c11f1ffc the `.travis.yml` contains `libxml2-utils`.
