### ISSUE TITLE
Message acknowledgement for program() destination ?

### ISSUE THREAD

**Issue by Adirelle** [balabit/syslog-ng#1152]
Not really an issue but a remark/question.

I was trying to write an external program that would take JSON message on stdin and insert them into ElasticSearch using the bulk API over HTTPS. It supposes to accumulate a certain number of messages (say 500) and push them using a single request. The whole process is obviously asynchronous, e.g. the fate of each individual messages is not immediately known, but it will eventually be.

Now, I want to keep that program simple enough. I do not want it to manage a persistent queue of messages in case the ES backend is down or unreachable.

I know syslog-ng handles such queues for some destinations, so here is the question : is there some way for the external program to acknowledge or to reject messages asynchronously, to avoid message loss ?

**Comment by bazsi** [comment]
Hi,

Well, the short answer is not right now.

You should probably embed our program into syslog-ng as a destination
driver, where you can write it in c, java or Python.

Bazsi
On Aug 5, 2016 1:47 PM, "Adirelle" <notifications@github.com> wrote:

Not really an issue but a remark/question.

I was trying to write an external program that would take JSON message on
stdin and insert them into ElasticSearch using the bull API over HTTPS. It
supposes to accumulate a certain number of messages (say 500) and push them
using a single request. The whole process is obviously asynchronous, e.g.
the fate of each individual messages is not immediately known, but it will
eventually be.

Now, I want to keep that program simple enough. I do not want it to manage
a persistent queue of messages in case the ES backend is down or
unreachable.

I know syslog-ng handles such queues for some destinations, so here is the
question : is there some way for the external program to acknowledge or to
reject messages asynchronously, to avoid message loss ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/balabit/syslog-ng/issues/1152>, or mute the thread

**Comment by presidento** [comment]
It seems the question was answered more than 1 year ago, so I'm closing this issue now.
