### ISSUE TITLE
Fix criterion-based unit tests

### ISSUE THREAD

**Issue by lbudai** [balabit/syslog-ng#1227]
Unit tests that call `app_startup` and `app_shutdown` on a per testcase basis are broken (this is why Travis failed for some of the PRs we have, I think). The testcases are run in a parallel way.

What can we do: call `app_startup` in a constructor (like in the `tests/unit/test_zone.c`).

**Comment by MrAnno** [comment]
Since Criterion uses [BoxFort](https://github.com/Snaipe/BoxFort) as a sandboxing library, the async app_startup() calls should not cause problems. BoxFort runs tests in isolated processes (I was wrong earlier).

I think this is a Criterion bug which was introduced in v2.3.0-rc1. I'll try to reproduce the issue in Travis with gdb attached.

**Comment by lbudai** [comment]
@MrAnno : any update on this?

**Comment by MrAnno** [comment]
The root cause has been found:
https://github.com/Snaipe/Criterion/issues/178

**Comment by MrAnno** [comment]
The fix is on the master branch of the BoxFort repo.
We should rebuild our Criterion package in OBS based on Snaipe/Criterion@c8d8faef.

**Comment by MrAnno** [comment]
Fixed.
@lbudai Thank you for updating the package.
