### ISSUE TITLE
Enhancement: syslog parser

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#1264]
The proposed change is isolate the syslog (rfc5424 and 3164) parsing code to be able to use it as an independant parser. This would allow more control in the configfile, e.g. for unhandled non-standard syslog messages:

```
source safe_syslog {
  channel {
    source {
      network(flags(no-parse););
    };
    channel { # handle standard syslog
      flags(final);
      parser {
        syslog();
      };
    };
    channel { # handle messages that fail to parse as rfc
      flags(fallback);
      [... do something different for unparseable syslog...]
    };  
  }
};
```

**Comment by bazsi** [comment]
Hi,

There's a syslog-parser() currently, isn't it what you mean? Although that
always succeeds, so it may not exactly be what you mean.

-- 
Bazsi

**Comment by faxm0dem** [comment]
I didn't know that! It's undocumented, is it?
If it fails I Guess it's easy to catch it with a filter

**Comment by bazsi** [comment]
It is documented here:

https://www.balabit.com/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html-single/index.html#parser-syslog

But indeed this may not be easy to grasp that it is not the builtin parsing
functionality of the syslog source, rather it is a separate parser.

**Comment by faxm0dem** [comment]
Indeed it is not clear to me at all. For instance, what are the possible options? @fekete-robert what's your opinion?
Right so I tried the following config:

```
@version: 3.8

destination d_stdout {
  file("/dev/stdout" template("$(format-json -s nv-pairs -s rfc5424)\n"));
};

source s_syslog {
  channel {
    source {
      file("/dev/stdin" flags(no-parse));
    };
    parser {
      syslog-parser(flags(syslog-protocol));
    };
  };
};

log {
  source(s_syslog);
  destination(d_stdout);
};
```

It seems to work, so I guess if you and @fekete-robert agree, we should turn this into a docbug.

**Comment by faxm0dem** [comment]
all things considered, I think the documentation just lacks an options paragraph, e.g.:

12.1.1. Options of syslog-parser

flags()
...

**Comment by fekete-robert** [comment]
So we should mention that 
 * the syslog-parser treats the message as RFC3164 by default
 * for RFC5424 messages, use syslog-parser(flags(syslog-protocol))

@bazsi We should make a website where the visitor pastes the message, and we attempt to parse it, and determine if it complies to a syslog RFC, where is the problem if not, and how we would fill the different macros from the message. I often see forum posts that have problems because of some non-standard message, and it's difficult to see where the problem is.

**Comment by fekete-robert** [comment]
So we should mention that 
 * the syslog-parser treats the message as RFC3164 by default
 * for RFC5424 messages, use syslog-parser(flags(syslog-protocol))

@bazsi We should make a website where the visitor pastes the message, and we attempt to parse it, and determine if it complies to a syslog RFC, where is the problem if not, and how we would fill the different macros from the message. I often see forum posts that have problems because of some non-standard message, and it's difficult to see where the problem is.

**Comment by fekete-robert** [comment]
@bazsi Does the syslog-parser have any other flags or options besides flags(syslog-protocol)?
