### ISSUE TITLE
multiple redis destination

### ISSUE THREAD

**Issue by simpleuser99** [balabit/syslog-ng#1275]
For one redis destination syslog-ng can only about 4000 events per second and this is very little for me. I need about 40k events syslog-ng to redis. 
When I use syslog-ng 3.7 I use multiple destination
```
destination d_redis {
    redis(
        host("localhost")
        port(6379)
        command("rpush" "pp_rtest" "${DATE} ${HOST} ${MSGHDR}${MSG}")
        throttle(0)
    );
};

destination d_redis1 {
    redis(
        host("localhost")
        port(6379)
        command("rpush" "pp_rtest" "${DATE} ${HOST} ${MSGHDR}${MSG}")
        throttle(0)
    );
};

destination d_redis2 {
    redis(
        host("localhost")
        port(6379)
        command("rpush" "pp_rtest" "${DATE} ${HOST} ${MSGHDR}${MSG}")
        throttle(0)
    );
};

destination d_redis3 {
    redis(
        host("localhost")
        port(6379)
        command("rpush" "pp_rtest" "${DATE} ${HOST} ${MSGHDR}${MSG}")
        throttle(0)
    );
};
```
And multiple filter
```
filter f_redis     { "$(% ${PID} 4)"  eq "0"  };
filter f_redis1     { "$(% ${PID} 4)"  eq "1"  };
filter f_redis2     { "$(% ${PID} 4)"  eq "2"  };
filter f_redis3     { "$(% ${PID} 4)"  eq "3"  };
```
```
log { source(s_ext); filter(f_redis); destination(d_redis); };
log { source(s_ext); filter(f_redis1); destination(d_redis1); };
log { source(s_ext); filter(f_redis2); destination(d_redis2); };
log { source(s_ext); filter(f_redis3); destination(d_redis3); };

```

When I update syslog-ng to 3.8.1 version I have the next error:

` Error checking the uniqueness of the persist names, please override it with persist-name option. Shutting down.; persist_name='redis(localhost,6379)', location='/etc/syslog-ng/conf.d/pg_to_redis.conf:31:5'`

How I can forwarder from syslog-ng to redis in one flow more than 4k events?
Or how I can use multiple redis destination like this I use it in syslog-ng ver 3.7 ?

**Comment by bazsi** [comment]
Just supply a unique persist-name option to redis, as recommended, and you
should be fine.

Also, if you are willing to do a perf record/report on Syslog-ng, we could
learn the reason it does only 4k/sec


On Dec 8, 2016 12:51, "simpleuser99" <notifications@github.com> wrote:

For one redis destination syslog-ng can only about 4000 events per second
and this is very little for me. I need about 40k events syslog-ng to redis.
When I use syslog-ng 3.7 I use multiple destination

destination d_redis {
    redis(
        host("localhost")
        port(6379)
        command("rpush" "pp_rtest" "${DATE} ${HOST} ${MSGHDR}${MSG}")
        throttle(0)
    );
};

destination d_redis1 {
    redis(
        host("localhost")
        port(6379)
        command("rpush" "pp_rtest" "${DATE} ${HOST} ${MSGHDR}${MSG}")
        throttle(0)
    );
};

destination d_redis2 {
    redis(
        host("localhost")
        port(6379)
        command("rpush" "pp_rtest" "${DATE} ${HOST} ${MSGHDR}${MSG}")
        throttle(0)
    );
};

destination d_redis3 {
    redis(
        host("localhost")
        port(6379)
        command("rpush" "pp_rtest" "${DATE} ${HOST} ${MSGHDR}${MSG}")
        throttle(0)
    );
};

And multiple filter

filter f_redis     { "$(% ${PID} 4)"  eq "0"  };
filter f_redis1     { "$(% ${PID} 4)"  eq "1"  };
filter f_redis2     { "$(% ${PID} 4)"  eq "2"  };
filter f_redis3     { "$(% ${PID} 4)"  eq "3"  };

log { source(s_ext); filter(f_redis); destination(d_redis); };
log { source(s_ext); filter(f_redis1); destination(d_redis1); };
log { source(s_ext); filter(f_redis2); destination(d_redis2); };
log { source(s_ext); filter(f_redis3); destination(d_redis3); };


When I update syslog-ng to 3.8.1 version I have the next error:

Error checking the uniqueness of the persist names, please override it with
persist-name option. Shutting down.; persist_name='redis(localhost,6379)',
location='/etc/syslog-ng/conf.d/pg_to_redis.conf:31:5'

How I can forwarder from syslog-ng to redis in one flow more than 4k events?
Or how I can use multiple redis destination like this I use it in syslog-ng
ver 3.7 ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/balabit/syslog-ng/issues/1275>, or mute the thread

**Comment by simpleuser99** [comment]
> Just supply a unique persist-name option to redis, as recommended, and you
> should be fine.

How? I have one redis in one ip adress and one port.

> Also, if you are willing to do a perf record/report on Syslog-ng, we could
> learn the reason it does only 4k/sec
How I can do it?

**Comment by simpleuser99** [comment]
You talked about persistent(yes) ? Right?
```
destination d_redis {
    redis(
        host("localhost")
        port(6379)
        command("rpush" "pp_rtest" "${DATE} ${HOST} ${MSGHDR}${MSG}")
        throttle(0)
        persistent(yes)
    );
};

destination d_redis1 {
    redis(
        host("localhost")
        port(6379)
        command("rpush" "pp_rtest" "${DATE} ${HOST} ${MSGHDR}${MSG}")
        throttle(0)
        persistent(yes)
    );
};

destination d_redis2 {
    redis(
        host("localhost")
        port(6379)
        command("rpush" "pp_rtest" "${DATE} ${HOST} ${MSGHDR}${MSG}")
        throttle(0)
        persistent(yes)
    );
};

destination d_redis3 {
    redis(
        host("localhost")
        port(6379)
        command("rpush" "pp_rtest" "${DATE} ${HOST} ${MSGHDR}${MSG}")
        throttle(0)
        persistent(yes)
    );
};
```

**Comment by juhaszviktor** [comment]
Hi,

You should use the  persist-name option
Something like similar:

destination d_redis {
    redis(
        host("localhost")
        port(6379)
        command("rpush" "pp_rtest" "${DATE} ${HOST} ${MSGHDR}${MSG}")
        persist-name("redis")
        throttle(0)
    );
};

destination d_redis1 {
    redis(
        host("localhost")
        port(6379)
        command("rpush" "pp_rtest" "${DATE} ${HOST} ${MSGHDR}${MSG}")
        persist-name("redis1")
        throttle(0)
    );
};

destination d_redis2 {
    redis(
        host("localhost")
        port(6379)
        command("rpush" "pp_rtest" "${DATE} ${HOST} ${MSGHDR}${MSG}")
        persist-name("redis2")
        throttle(0)
    );
};

destination d_redis3 {
    redis(
        host("localhost")
        port(6379)
        command("rpush" "pp_rtest" "${DATE} ${HOST} ${MSGHDR}${MSG}")
        persist-name("redis3")
        throttle(0)
    );
};


BR,

Viktor

**Comment by simpleuser99** [comment]
juhaszviktor many thanks. This work or me.
