### ISSUE TITLE
systemd-journal not found

### ISSUE THREAD

**Issue by igenyar** [balabit/syslog-ng#1329]
# syslog-ng

This is a similar problem to https://github.com/balabit/syslog-ng/issues/914, but I am not sure if it is addressed or may not for different OS?

## Version of syslog-ng

```
output of syslog-ng --version
syslog-ng 3.8.alpha0
Installer-Version: 3.8.alpha0
Revision: 3.8.alpha0
Module-Directory: /usr/local/lib/syslog-ng
Module-Path: /usr/local/lib/syslog-ng
Available-Modules: affile,afsocket,afprog,graphite,date,afstomp,cryptofuncs,afuser,cef,syslogformat,dbparser,linux-kmsg-format,disk-buffer,system-source,pacctformat,kvformat,pseudofile,add_contextual_data,csvparser,basicfuncs,confgen
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off
```

## Platform

Name and version of OS: Ubuntu 16.04

# Issue

systemd-journal

## Failure

```
$ gdb syslog-ng
 run
Error parsing source, source plugin systemd-journal not found in /usr/local/etc/syslog-ng.conf at line 11, column 9:

        systemd-journal();
        ^^^^^^^^^^^^^^^

syslog-ng documentation: https://www.balabit.com/support/documentation?product=syslog-ng-ose
mailing list: https://lists.balabit.hu/mailman/listinfo/syslog-ng
```

## Steps to reproduce

1. edit syslog-ng.conf

2. start syslog-ng

## Configuration

```
$ cat /path/to/syslog-ng.conf
#############################################################################
# Default syslog-ng.conf file which collects all local logs into a
# single file called /var/log/messages.
#

@version: 3.9
@include "scl.conf"

source s_local {
	system();
        systemd-journal();
	internal();
};

source s_network {
	udp();
};

destination d_local {
	file("/var/log/messages");
};

log {
	source(s_local);

	# uncomment this line to open port 514 to receive messages
	#source(s_network);
	destination(d_local);
};
```

## Other info

I can't find systemd-journal lib, why?
```
$ ls /usr/local/lib/syslog-ng/
libadd_contextual_data.so  libafstomp.so     libconfgen.so      libdbparser.so     liblinux-kmsg-format.so  libsyslog-ng.so.3.8.alpha0
libaffile.so               libafuser.so      libcryptofuncs.so  libdisk-buffer.so  libpacctformat.so        libsystem-source.so
libafprog.so               libbasicfuncs.so  libcsvparser.so    libgraphite.so     libpseudofile.so
libafsocket.so             libcef.so         libdate.so         libkvformat.so     libsyslogformat.so
```

cmake shows missing something, does it matter?
```
$ cmake .
...
-- Could NOT find LIBNET (missing:  LIBNET_LIBRARIES LIBNET_DEFINES LIBNET_FOUND) 
-- Could NOT find WRAP (missing:  WRAP_LIBRARY WRAP_INCLUDE_DIR) 
-- Checking for module 'libpcre'
--   Found libpcre, version 8.38
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for one of the modules 'hiredis'
-- Could NOT find Hiredis (missing:  HIREDIS_LIBRARIES HIREDIS_INCLUDE_DIR) 
-- Could NOT find ESMTP (missing:  ESMTP_INCLUDE_DIR ESMTP_LIBRARIES) 
-- Performing Test SYSLOG_NG_HAVE_CTRLBUF_IN_MSGHDR
-- Performing Test SYSLOG_NG_HAVE_CTRLBUF_IN_MSGHDR - Success
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Could NOT find LibGeoIP (missing:  LibGeoIP_LIBRARY LibGeoIP_INCLUDE_DIR) 
-- Could NOT find JSONC (missing:  JSONC_LIBRARIES JSONC_INCLUDE_DIRS) 
-- Could NOT find LibDbi (missing:  LIBDBI_LIBRARY LIBDBI_INCLUDE_DIR) 
-- Looking for sys/strlog.h
-- Looking for sys/strlog.h - not found
-- Looking for stropts.h
-- Looking for stropts.h - found
-- Could NOT find PythonLibs (missing:  PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) 
-- Could NOT find Java (missing:  Java_JAVA_EXECUTABLE Java_JAR_EXECUTABLE Java_JAVAC_EXECUTABLE Java_JAVAH_EXECUTABLE Java_JAVADOC_EXECUTABLE) (Required is at least version "1.7")
-- Could NOT find JNI (missing:  JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) 
-- Could NOT find Gradle (missing:  GRADLE_EXECUTABLE) (Required is at least version "2.2")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mezzanine/syslog-ng
```

**Comment by bazsi** [comment]
Your version seems to be 3.8 alpha2, whereas 3.8.1 is the latest release in
that branch and theres even 3.9.1.

**Comment by igenyar** [comment]
@bazsi, I clone from "https://github.com/balabit/syslog-ng.git" as recommended by https://www.balabit.com/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/compiling-syslog-ng.html

```
commit: 5f83742652bd7e1400b65ed37366afb72032a24b
Merge: e6b7459 c7c5a29
Author: Balazs Scheidler <balazs.scheidler@balabit.com>
Date:   Sun Jan 22 14:59:21 2017 +0100
```

After build,
```
~/syslog-ng$ ./syslog-ng/syslog-ng --version
syslog-ng 3.8.alpha0
Installer-Version: 3.8.alpha0
Revision: 3.8.alpha0
Module-Directory: /usr/local/lib/syslog-ng
Module-Path: /usr/local/lib/syslog-ng
Available-Modules: affile,afsocket,afprog,graphite,date,afstomp,cryptofuncs,afuser,cef,syslogformat,dbparser,linux-kmsg-format,disk-buffer,system-source,pacctformat,kvformat,pseudofile,add_contextual_data,csvparser,basicfuncs,confgen
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off
```

So if it is not the latest, where to get the latest?

Thanks.

**Comment by igenyar** [comment]
This is what I try.
```
$ git checkout -b 3.9 syslog-ng-3.9.1
$ cmake . ; make
$ ./syslog-ng/syslog-ng --version
```

still 3.8.alpha0

**Comment by bazsi** [comment]
Well, that indeed seems to be the latest. But if you run autogen.sh and the
configure script, the version should be read from the file VERSION which
contains 3.9.1 for me.

Can you check the feature listing of the configure script? E.g. the end of
the output. Also config.status and config.log can help diagnosing both your
original problem and the version issue.


On Jan 25, 2017 18:46, "igenyar" <notifications@github.com> wrote:

@bazsi <https://github.com/bazsi>, I clone from "
https://github.com/balabit/syslog-ng.git" as recommended by
https://www.balabit.com/documents/syslog-ng-ose-latest-
guides/en/syslog-ng-ose-guide-admin/html/compiling-syslog-ng.html

commit: 5f83742652bd7e1400b65ed37366afb72032a24b
Merge: e6b7459 c7c5a29
Author: Balazs Scheidler <balazs.scheidler@balabit.com>
Date:   Sun Jan 22 14:59:21 2017 +0100

After build,

~/syslog-ng$ ./syslog-ng/syslog-ng --version
syslog-ng 3.8.alpha0
Installer-Version: 3.8.alpha0
Revision: 3.8.alpha0
Module-Directory: /usr/local/lib/syslog-ng
Module-Path: /usr/local/lib/syslog-ng
Available-Modules:
affile,afsocket,afprog,graphite,date,afstomp,cryptofuncs,afuser,cef,syslogformat,dbparser,linux-kmsg-format,disk-buffer,system-source,pacctformat,kvformat,pseudofile,add_contextual_data,csvparser,basicfuncs,confgen
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off

So if it is not the latest, where to get the latest?

Thanks.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/balabit/syslog-ng/issues/1329#issuecomment-275179409>,
or mute the thread

**Comment by igenyar** [comment]
Works great! All I miss is "autogen.sh". Thanks a lot! You may proceed to close.
