### ISSUE TITLE
syslog-ng start fails: "Plugin module not found in 'module-path'; module-path='//usr/lib64/syslog-ng', module='mod-java'"

### ISSUE THREAD

**Issue by chandnishankar08** [balabit/syslog-ng#1356]
output of syslog-ng --version
```
syslog-ng 3.9.1
Installer-Version: 3.9.1
Revision: 
Module-Directory: /usr/local/lib/syslog-ng
Module-Path: /usr/local/lib/syslog-ng
Available-Modules: afuser,syslogformat,afmongodb,afstomp,disk-buffer,afprog,cryptofuncs,pseudofile,linux-kmsg-format,basicfuncs,dbparser,graphite,system-source,csvparser,afsocket,cef,curl,mod-java,confgen,afamqp,affile,add-contextual-data,date,kvformat
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off

# Issue
syslog-ng fails to start

## Failure
service syslog-ng start
[2017-02-23T15:38:38.039379] Plugin module not found in 'module-path'; module-path='//usr/lib64/syslog-ng', module='mod-java'
Error parsing destination, destination plugin java not found in destination block kafka at line 2, column 3:
                                                  included from /etc/syslog-ng/syslog-ng.conf line 65, column 4

  java
  ^^^^

PFB the lines in syslog-ng.conf
destination d_kafka {
  kafka(
     client-lib-dir("/usr/local/lib/syslog-ng/java-modules/*.jar:/opt/kafka_2.12-0.10.2.0/libs/*.jar")
     kafka-bootstrap-servers("1.2.3.4:9092,192.168.0.2:9092")
     topic("${HOST}")
   );
};

**Comment by lbudai** [comment]
It seems you don't have java support.
How did you install syslog-ng?

**Comment by chandnishankar08** [comment]
Thank you for your response.
I had used yum to install it. However I reinstalled from binaries and it is now working.

**Comment by dochakovsky** [comment]
Hi chandnishankar08 ,
Could you please provide more information about how exactly you fixed it? I installed it from binaries, got this exact error. Reinstalled again on another server and got exactly the same error. I was installing from 3rd party binaries (tried the latest stable build and the latest weekly build).... Don't understand what is wrong.

**Comment by dochakovsky** [comment]
I found a way to make it working:

Instead using this command to restart syslog-ng: 
systemctl restart syslog-ng

I executed these 2 commands:
systemctl stop syslog-ng
/usr/sbin/syslog-ng -Fvde

The last command is able to start Syslog NG without any issues and it is producing messages into KAFKA.

**Comment by szemere** [comment]
Hello @dochakovsky ,
 I am glad this is working for you now. Just a couple of notes about the workaround:

 The -v option is stand for "verbose" which will cause unnecessary load in your case.
 The -d option is stand for "debug", same case here.
 The -e option redirects the output to stderr.
 Please investigate the output of `syslog-ng --help-all` to find the best options for your use case.

 note: I think the root cause for your problem might be the difference between the list of the available environment variables in case of starting a program as a service or by a user. Please check the JAVA_HOME environment variable.

Br,
Laci

**Comment by dochakovsky** [comment]
Hi Laci,
You're right, looks like systemctl requires some additional configuration. I am able to run Syslog-NG by executing: /usr/sbin/syslog-ng (without any flags) which is totally fine for me now.
Thanks.

**Comment by momo1123** [comment]
Syslog-ng version: syslog-ng 3 (3.23.1)
Linux Version: AlmaLinux release 8.4 (Electric Cheetah)

I was having a similar issue but with the HTTP module:
Plugin module not found in 'module-path'; module-path='/usr/lib64/syslog-ng', module='http'
RESOLUTION:
I ran 'dnf install syslog-ng-http'  or 'yum install syslog-ng-http' which installed the syslog-ng http module and the issue is resolved.

**Comment by bazsi** [comment]
syslog-ng-java is not needed for http support anymore. I am not sure when the switch happened but it's been years. 

Fyi: syslog-ng is at 4.2 now, but before 4.0 was introduced we had 3.38, so 3.23 is like 17 releases old, with roughly 2months per release that's 34 months.
