### ISSUE TITLE
patterndb parser: PROGRAM and MSG should be configurable

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#141]
Currently the patterndb parser enforces the use of the following macros:
- `$PROGRAM` for the _ruleset patterns_
- `$MESSAGE` for the _rule patterns_

The latter is not entirely true, as it seems to be possible according to the _source_ to use `template()` in a `db_parser` block. It is however not officially possible, from reading the docs.

Nevertheless I have the strong feeling this is an unnecessary limitation that could be easily lifted without hacking the config (copy whatever is in `$custom_message` into `$MESSAGE` and same for `*PROGRAM`). This is particularily true when using _e.g._ _JSON_ formatted input.

```
parser p_new_pdb {
  file("/var/lib/syslog-ng/patterndb/default.xml")
  message_template("$my_message")
  program_template("$my_program")
};
```

**Comment by ihrwein** [comment]
I just checked this. The `template()` parameter should be supported by dbparser and it's the same as your `message_template()`. Aliasing it is easy.

The `program_template()` doesn't exists, yet. Do you think this is dbparser specific or general enough to be supported by all parsers?

**Comment by faxm0dem** [comment]
program_template seems very specific to dbparser, as others only use one template.
If one were to generalize this, it would probably make more sense to allow for `template` to be passed an array, e.g. `[$MSG, $PROGRAM, ...]`

**Comment by bazsi** [comment]
I think this is a good short term feature. I originally wanted to make
db-parser n dimensional, each making it possible which nvpair it would use
for matching.

But I think we don't want that but rather add this kind of filtering into
the config.

**Comment by hadret** [comment]
I'm not 100% sure whether my case apply here as well, but by the overall look of it it seems so. I'm having a structured way of `$PROGRAM` name that I need to parse in order to aggregate logs the way I want to. Logs themselves can originate from the same and/or different hosts (multiple instances per host) at the same time, so I went with the following patter for the `$PROGRAM`: `app_part1/app_part2/app_part3`. The first two parts are the same for every instance, the differentiating factor is the third part. I wanted to have the following structure in the logs tree: `/var/log/`app_part1`/`app_part2`.log -- but in order to be able to do that, I would need to be able to parse `$PROGRAM`, which is, to my understanding, currently impossible.

**Comment by bazsi** [comment]
No, its not. The ruleset level pattern refers to the program name and you
can use the same pattern language there.

On Jun 21, 2017 12:03 PM, "Filip Chabik" <notifications@github.com> wrote:

I'm not 100% sure whether my case apply here as well, but by the overall
look of it it seems so. I'm having a structured way of $PROGRAM name that I
need to parse in order to aggregate logs the way I want to. Logs themselves
can originate from the same and/or different hosts (multiple instances per
host) at the same time, so I went with the following patter for the $PROGRAM:
app_part1/app_part2/app_part3. The first two parts are the same for every
instance, the differentiating factor is the third part. I wanted to have
the following structure in the logs tree: /var/log/app_part1/app_part2.log
-- but in order to be able to do that, I would need to be able to
parse$PROGRAM`,
which is, to my understanding, currently impossible.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/balabit/syslog-ng/issues/141#issuecomment-310031841>,
or mute the thread
