### ISSUE TITLE
Missing SDATA and SEQNUM in custom java destination

### ISSUE THREAD

**Issue by kirill133** [balabit/syslog-ng#1410]
# syslog-ng
## Version of syslog-ng
```
syslog-ng 3.9.1
Installer-Version: 3.9.1
Revision: 
Module-Directory: /usr/local/lib/syslog-ng
Module-Path: /usr/local/lib/syslog-ng
Available-Modules: affile,afuser,add-contextual-data,afmongodb,curl,pseudofile,afstomp,csvparser,disk-buffer,system-source,mod-java,cef,cryptofuncs,sdjournal,afsocket,linux-kmsg-format,date,kvformat,syslogformat,basicfuncs,dbparser,graphite,confgen,afprog,afamqp
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off
```

## Platform

Ubuntu 16.04

# Issue

## Failure
I'm writing custom (AWS SQS) java destination (using kafka destination as example and by extending StructuredLogDestination class).
And looks like LogMessage object does not contain any of the values below:
```
public class SqsDestination extends StructuredLogDestination {
...
    @Override
    protected boolean send(LogMessage logMessage) {
...
        InternalMessageSender.debug("SDATA: " + logMessage.getValue("SDATA"));
        InternalMessageSender.debug("${SDATA}: " + logMessage.getValue("${SDATA}"));
        InternalMessageSender.debug("STRUCTURED-DATA: " + logMessage.getValue("STRUCTURED-DATA"));
        InternalMessageSender.debug("SEQNUM: " + logMessage.getValue("SEQNUM"));
        InternalMessageSender.debug(".SDATA.meta.sequenceId: " + logMessage.getValue(".SDATA.meta.sequenceId"));
...
```
The response is empty for all above values.
At the same time MSG, MSGHDR are filled correctly.
And at the same time standard file(...) destination prints SDATA correctly

## Steps to reproduce

1. Extend StructuredLogDestination.java
2. Implement method protected boolean send(LogMessage logMessage)
3. Configure destination in syslog-ng.conf as java destination:
```
  java(
    class_path("...syslog-ng-sqs-all-0.0.1.jar")
    class_name("...SqsDestination")
...
    option("queueName", "syslog-ng-test")
    option("template", "<${PRI:--}>1 ${ISODATE:--} ${FULLHOST_FROM:--} ${PROGRAM:--} ${PID:--} ${MSGID:--} ${SDATA:--} ${MSG:--}\n")
...
 );
```
4. Print logMessage.getValue("SDATA") from Java and other keys (see above example)
5. Start syslog-ng with debug info ($ syslog-ng -Fd)
6. Send some message ($ logger aaa)
7. SDATA and SEQNUM are empty in syslog console or after applying options.getTemplate().getResolvedString(...)

## Input and output logs (if possible)
[2017-04-03T18:38:04.168151] SDATA: ;
[2017-04-03T18:38:04.168186] ${SDATA}: ;
[2017-04-03T18:38:04.168209] STRUCTURED-DATA: ;
[2017-04-03T18:38:04.168246] SEQNUM: ;
[2017-04-03T18:38:04.168284] .SDATA.meta.sequenceId: ;
[2017-04-03T18:38:04.168319] MSG: aaa;
[2017-04-03T18:38:04.168354] MSGHDR: user1[20657]: ;

**Comment by furiel** [comment]
If you want to evaluate macros: $SDATA, $SEQNUM, then you need to use LogTemplate class. Using getValue, you can only fetch key value pairs. To evalue these macros, you can use for example:
```
LogTemplate logTemplate = new LogTemplate(getConfigHandle());
logTemplate.compile("${SDATA}\n");
InternalMessageSender.debug(logTemplate.format(logMessage, 0, logTemplate.LTZ_SEND));
```

But this line works for me:
```
        InternalMessageSender.debug(".SDATA.meta.sequenceId: " + logMessage.getValue(".SDATA.meta.sequenceId"));
```
If you ran into trouble with this, most probably the sequence id was not parsed from your message. Please make sure you use flags(syslog-protocol) in your source like:
```
 source s_file {
   file("/tmp/input" flags(syslog-protocol));
};
```
and your test message must be formatted with syslog-protocol. For example this message worked for me:
```
<34>1 2003-10-11T22:14:15.003Z mymachine.example.com su - ID47 [meta sequenceId="213"] BOM'su root' failed for lonvick on /dev/pts/8
```
Now with $SEQNUM: you will need to use LogTemplate here similarly to $SDATA. But this will not work though yet, because for now LogTemplate passes zero into the sequence number unconditionally. As this parameter is not something that comes from configuration, but it is controlled by threaded destination driver, somehow this value needs to be propagated to the LogDestination class, and then one can add it in LogTemplate as a parameter. I will create a pull request for this issue.

Thanks for reporting!
