### ISSUE TITLE
syslog-ng 3.9.1 segfault 

### ISSUE THREAD

**Issue by Andre188** [balabit/syslog-ng#1453]
## Version of syslog-ng
syslog-ng 3.9.1
Installer-Version: 3.9.1
Revision: 
Module-Directory: //usr/lib64/syslog-ng
Module-Path: //usr/lib64/syslog-ng
Available-Modules: add-contextual-data,affile,afprog,afsocket,afstomp,afuser,basicfuncs,cef,confgen,cryptofuncs,csvparser,date,dbparser,disk-buffer,graphite,json-plugin,kvformat,linux-kmsg-format,pseudofile,sdjournal,syslogformat,system-source,mod-python,geoip-plugin,afamqp
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on

## Platform
CentOS Linux release 7.3.1611 (Core)

# Issue
Syslog-ng segfaults under load with embedded python and patterndb running. 

## Failure
<6>1 2017-04-27T23:23:25+00:00 ip-172-31-49-170.ec2.internal kernel - - - syslog-ng[21326]: segfault at a ip 00007fbf84a1b5be sp 00007fbf56ff98c0 error 4 in libsyslog-ng-3.9.so.0.0.0[7fbf849b9000+a1000]
<6>1 2017-04-27T23:23:36+00:00 ip-172-31-49-170.ec2.internal kernel - - - syslog-ng[22066]: segfault at 7f7770090cb2 ip 00007f7703519d5c sp 00007f76ddff7b40 error 6 in libsyslog-ng-3.9.so.0.0.0[7f77034ac000+a1000]
<6>1 2017-04-27T23:24:20+00:00 ip-172-31-49-170.ec2.internal kernel - - - syslog-ng[22283]: segfault at 0 ip 00007f6fa4cc0b10 sp 00007f6f537fa9b8 error 4 in libsyslog-ng-3.9.so.0.0.0[7f6fa4c57000+a1000]
<6>1 2017-04-27T23:24:31+00:00 ip-172-31-49-170.ec2.internal kernel - - - syslog-ng[22321]: segfault at 79 ip 00007f241bc815ba sp 00007f23eeff9a20 error 4 in libsyslog-ng-3.9.so.0.0.0[7f241bc1f000+a1000]
<6>1 2017-04-27T23:24:41+00:00 ip-172-31-49-170.ec2.internal kernel - - - syslog-ng[22370]: segfault at a ip 00007fedf25135be sp 00007fedcf7faa20 error 4
<6>1 2017-04-27T23:24:41+00:00 ip-172-31-49-170.ec2.internal kernel - - - syslog-ng[22368]: segfault at 7fee680802bf ip 00007fedf251ed5c sp 00007fedd4ff5b40 error 6
<6>1 2017-04-27T23:43:47+00:00 ip-172-31-49-170.ec2.internal kernel - - - syslog-ng[23660]: segfault at 0 ip 00007fd0bb04cb10 sp 00007fd0a936c9b8 error 4 in libsyslog-ng-3.9.so.0.0.0[7fd0bafe3000+a1000]
<6>1 2017-04-27T23:45:10+00:00 ip-172-31-49-170.ec2.internal kernel - - - syslog-ng[23754]: segfault at a ip 00007fce972175be sp 00007ffc571637b0 error 4 in libsyslog-ng-3.9.so.0.0.0[7fce971b5000+a1000]
<6>1 2017-04-27T23:45:31+00:00 ip-172-31-49-170.ec2.internal kernel - - - syslog-ng[23943]: segfault at 7fc338146c99 ip 00007fc33edf0d5c sp 00007fc32c90bb40 error 6 in libsyslog-ng-3.9.so.0.0.0[7fc33ed83000+a1000]
<6>1 2017-04-27T23:45:53+00:00 ip-172-31-49-170.ec2.internal kernel - - - syslog-ng[24044]: segfault at 0 ip 00007f9fbd6cfb10 sp 00007f9fa4ff59b8 error 4 in libsyslog-ng-3.9.so.0.0.0[7f9fbd666000+a1000]

I can add more details if you could provide directions to troubleshoot/debug this.
Thank you again for your help.

**Comment by bazsi** [comment]
We would need a backtrace of the crash. That is pls make sure that you have
debug symbols (they are the debuginfo packages on centos), enable core
files using the --enable-core command line option or "ulimit -c unlimited",
make sure syslog-ng runs in a directory it has write permissions to.

All this before starting, make sure that these get applied to the syslog-ng
process, and not the shell you invoke systemctl.

The best if you stop the service, and start the syslog-ng process manually
from the shell with a command line that matches your production instance.

Once you have the core, you can produce a backtrace using:

$ gdb syslog-ng core
(gdb) bt full

Dont delete the core, we might have additional questions while
troubleshooting.

An alternative to this, if you send the binaries, the debuginfo, the system
libs syslog-ng links to and the core file our way. This can also be
required for more tricky cases.

Bazsi

On Apr 28, 2017 02:37, "Andre188" <notifications@github.com> wrote:

Version of syslog-ng

syslog-ng 3.9.1
Installer-Version: 3.9.1
Revision:
Module-Directory: //usr/lib64/syslog-ng
Module-Path: //usr/lib64/syslog-ng
Available-Modules: add-contextual-data,affile,afprog,afsocket,afstomp,
afuser,basicfuncs,cef,confgen,cryptofuncs,csvparser,date,
dbparser,disk-buffer,graphite,json-plugin,kvformat,linux-
kmsg-format,pseudofile,sdjournal,syslogformat,system-
source,mod-python,geoip-plugin,afamqp
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Platform

CentOS Linux release 7.3.1611 (Core)
Issue

Syslog-ng segfaults under load with embedded python and patterndb running.
Failure

<6>1 2017-04-27T23:23:25+00:00 ip-172-31-49-170.ec2.internal kernel - - -
syslog-ng[21326]: segfault at a ip 00007fbf84a1b5be sp 00007fbf56ff98c0
error 4 in libsyslog-ng-3.9.so.0.0.0[7fbf849b9000+a1000]
<6>1 2017-04-27T23:23:36+00:00 ip-172-31-49-170.ec2.internal kernel - - -
syslog-ng[22066]: segfault at 7f7770090cb2 ip 00007f7703519d5c sp
00007f76ddff7b40 error 6 in libsyslog-ng-3.9.so.0.0.0[7f77034ac000+a1000]
<6>1 2017-04-27T23:24:20+00:00 ip-172-31-49-170.ec2.internal kernel - - -
syslog-ng[22283]: segfault at 0 ip 00007f6fa4cc0b10 sp 00007f6f537fa9b8
error 4 in libsyslog-ng-3.9.so.0.0.0[7f6fa4c57000+a1000]
<6>1 2017-04-27T23:24:31+00:00 ip-172-31-49-170.ec2.internal kernel - - -
syslog-ng[22321]: segfault at 79 ip 00007f241bc815ba sp 00007f23eeff9a20
error 4 in libsyslog-ng-3.9.so.0.0.0[7f241bc1f000+a1000]
<6>1 2017-04-27T23:24:41+00:00 ip-172-31-49-170.ec2.internal kernel - - -
syslog-ng[22370]: segfault at a ip 00007fedf25135be sp 00007fedcf7faa20
error 4
<6>1 2017-04-27T23:24:41+00:00 ip-172-31-49-170.ec2.internal kernel - - -
syslog-ng[22368]: segfault at 7fee680802bf ip 00007fedf251ed5c sp
00007fedd4ff5b40 error 6
<6>1 2017-04-27T23:43:47+00:00 ip-172-31-49-170.ec2.internal kernel - - -
syslog-ng[23660]: segfault at 0 ip 00007fd0bb04cb10 sp 00007fd0a936c9b8
error 4 in libsyslog-ng-3.9.so.0.0.0[7fd0bafe3000+a1000]
<6>1 2017-04-27T23:45:10+00:00 ip-172-31-49-170.ec2.internal kernel - - -
syslog-ng[23754]: segfault at a ip 00007fce972175be sp 00007ffc571637b0
error 4 in libsyslog-ng-3.9.so.0.0.0[7fce971b5000+a1000]
<6>1 2017-04-27T23:45:31+00:00 ip-172-31-49-170.ec2.internal kernel - - -
syslog-ng[23943]: segfault at 7fc338146c99 ip 00007fc33edf0d5c sp
00007fc32c90bb40 error 6 in libsyslog-ng-3.9.so.0.0.0[7fc33ed83000+a1000]
<6>1 2017-04-27T23:45:53+00:00 ip-172-31-49-170.ec2.internal kernel - - -
syslog-ng[24044]: segfault at 0 ip 00007f9fbd6cfb10 sp 00007f9fa4ff59b8
error 4 in libsyslog-ng-3.9.so.0.0.0[7f9fbd666000+a1000]

I can add more details if you could provide directions to
troubleshoot/debug this.
Thank you again for your help.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/balabit/syslog-ng/issues/1453>, or mute the thread

**Comment by supericeboy** [comment]
I am working with  Andre188. Here is the BT
[gdb.txt](https://github.com/balabit/syslog-ng/files/973811/gdb.txt)

**Comment by Andre188** [comment]
This appears to be fixed in 3.10. I have not been able to reproduce the issue in that version.
