### ISSUE TITLE
json-plugin is not loaded 

### ISSUE THREAD

**Issue by giedriusramas** [balabit/syslog-ng#1534]
## Version of syslog-ng

```
syslog-ng 3.9.1
Installer-Version: 3.9.1
Revision: 3.9.1-2
Module-Directory: /usr/lib/syslog-ng/3.9
Module-Path: /usr/lib/syslog-ng/3.9
Available-Modules: curl,confgen,affile,dbparser,pseudofile,afuser,geoip-plugin,kvformat,afstomp,afsmtp,csvparser,cef,afamqp,date,system-source,basicfuncs,disk-buffer,linux-kmsg-format,graphite,afsql,afmongodb,sdjournal,syslogformat,afsocket,add-contextual-data,cryptofuncs,afprog
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on

```

## Platform

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

# Issue
I am not able to get json-plugin loaded

```
dpkg -l | grep syslog-ng-mod-json
ii  syslog-ng-mod-json                 3.9.1-2                                    amd64        Enhanced system logging daemon (JSON plugin)
```

```
 syslog-ng --module-registry
Module: json-plugin
Status: Unable to dlopen shared object, probably not a syslog-ng module
```

**Comment by furiel** [comment]
@giedriusramas could you please check the relevant apt sources list file? Probably 16.10 was added  instead of 16.04.
For xenial, you need to use
deb http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_16.04 ./

Another things to check:
Please make sure libjson-c2 is installed.

Also, if you start syslog-ng with debug, you can get a little more elaborate information why the plugin load failed.
For example if I use wrong version of apt repository (Yakketi), I could see this one after starting with syslog-ng -Fed
[...]
 [2017-07-31T09:24:34.345319] Error opening plugin module; module='json-plugin', error='libjson-c.so.3: cannot open shared object file: No such file or directory'
[...]
which is normal for a xenial, because there is only libjson-c.so.2

**Comment by giedriusramas** [comment]
Yes it was the problem of wrong apt-source list.  Changed to 16.04 and everything is fine now.
