### ISSUE TITLE
Incorrect timestamps on system with musl libc

### ISSUE THREAD

**Issue by stintel** [balabit/syslog-ng#1581]
# syslog-ng

## Version of syslog-ng
```
syslog-ng 3.10.1
Installer-Version: 3.10.1
Revision:
Module-Directory: /usr/lib/syslog-ng
Module-Path: /usr/lib/syslog-ng
Available-Modules: snmptrapd-parser,stardate,map-value-pairs,add-contextual-data,cef,disk-buffer,kvformat,date,graphite,pseudofile,linux-kmsg-format,dbparser,afstomp,basicfuncs,cryptofuncs,confgen,system-source,affile,http,csvparser,afsocket,afprog,afuser,syslogformat
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
```

## Platform
Gentoo Hardened musl

# Issue
When running syslog-ng on a system with musl libc, the timestamps in the logs are incorrect. The kernel and syslog-ng log entries have the correct timestamp (in the local timezone), but everything else seems to have timestamps in UTC. This does not happen on a system with glibc and the exact same syslog-ng configuration. A quick test with rsyslog on the same musl system also did not show this behaviour.

## Steps to reproduce
1. start syslog-ng on a system with musl libc
2. check timestamps in /var/log/messages

## Configuration
/etc/syslog-ng/syslog-ng.conf:
```
@version: 3.10
#
# Syslog-ng default configuration file for Gentoo Linux

## https://bugs.gentoo.org/show_bug.cgi?id=426814
@include "scl.conf"

options {
        threaded(yes);
        chain_hostnames(no);

        # The default action of syslog-ng is to log a STATS line
        # to the file every 10 minutes.  That's pretty ugly after a while.
        # Change it to every 12 hours so you get a nice daily update of
        # how many messages syslog-ng missed (0).
        stats_freq(43200);
        # The default action of syslog-ng is to log a MARK line
        # to the file every 20 minutes.  That's seems high for most
        # people so turn it down to once an hour.  Set it to zero
        # if you don't want the functionality at all.
        mark_freq(3600);
};

source src { system(); internal(); };

destination messages { file("/var/log/messages"); };

# By default messages are logged to tty12...
destination console_all { file("/dev/tty12"); };
# ...if you intend to use /dev/console for programs like xconsole
# you can comment out the destination line above that references /dev/tty12
# and uncomment the line below.
#destination console_all { file("/dev/console"); };

log { source(src); destination(messages); };
log { source(src); destination(console_all); };
```

## Input and output logs (if possible)
```
Jul  3 06:46:59 musltoo syslog-ng[1454]: syslog-ng starting up; version='3.10.1'
Jul  3 04:46:59 musltoo crond[1482]: (CRON) STARTUP (1.5.0)
Jul  3 04:46:59 musltoo crond[1482]: (CRON) INFO (RANDOM_DELAY will be scaled with factor 98% if used.)
Jul  3 04:46:59 musltoo crond[1482]: (CRON) INFO (running with inotify support)
Jul  3 06:46:59 musltoo kernel: ip_set: protocol 6
Jul  3 06:46:59 musltoo kernel: ip_tables: (C) 2000-2006 Netfilter Core Team
Jul  3 06:46:59 musltoo kernel: nf_conntrack version 0.5.0 (65536 buckets, 262144 max)
Jul  3 04:47:04 musltoo /etc/init.d/net.eth1[1887]: config_eth1 not specified; defaulting to DHCP
Jul  3 04:47:07 musltoo haveged[2017]: haveged starting up
Jul  3 04:47:07 musltoo haveged[2019]: haveged: ver: 1.9.1; arch: x86; vend: GenuineIntel; build: (gcc 5.4.0 ITV); collect: 128K
Jul  3 04:47:07 musltoo haveged[2019]: haveged: cpu: (L4 VC); data: 32K (L2 L4 V); inst: 32K (L2 L4 V); idx: 21/40; sz: 31924/59119
Jul  3 04:47:07 musltoo haveged[2019]: haveged: tot tests(BA8): A:1/1 B:1/1 continuous tests(B):  last entropy estimate 8.00105
Jul  3 04:47:07 musltoo haveged[2019]: haveged: fills: 0, generated: 0
Jul  3 06:47:07 musltoo kernel: random: crng init done
Jul  3 04:47:10 musltoo /etc/init.d/mysql[2092]: You don't appear to have the mysql database installed yet.
Jul  3 04:47:10 musltoo /etc/init.d/mysql[2093]: Please run `emerge --config =dev-db/percona-server-5.6.36.82.0` to have this done...
Jul  3 04:47:10 musltoo /etc/init.d/mysql[2025]: ERROR: mysql failed to start
Jul  3 04:47:12 musltoo /etc/init.d/php-fpm[2158]: ERROR: php-fpm failed to start
Jul  3 04:47:12 musltoo /etc/init.d/xinetd[2251]: /etc/init.d/xinetd uses runscript, please convert to openrc-run.
Jul  3 06:47:12 musltoo kernel: sctp: Hash tables configured (bind 256/256)
Jul  3 06:47:12 musltoo kernel: alg: No test for __sha1-mb (__intel_sha1-mb)
Jul  3 06:47:12 musltoo kernel: alg: No test for __sha1-mb (mcryptd(__intel_sha1-mb))
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration file: /etc/xinetd.d/chargen-dgram [file=/etc/xinetd.conf] [line=49]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration file: /etc/xinetd.d/chargen-stream [file=/etc/xinetd.d/chargen-stream] [line=67]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration file: /etc/xinetd.d/check_mk [file=/etc/xinetd.d/check_mk] [line=67]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration file: /etc/xinetd.d/daytime-dgram [file=/etc/xinetd.d/daytime-dgram] [line=52]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration file: /etc/xinetd.d/daytime-stream [file=/etc/xinetd.d/daytime-stream] [line=67]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration file: /etc/xinetd.d/discard-dgram [file=/etc/xinetd.d/discard-dgram] [line=67]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration file: /etc/xinetd.d/discard-stream [file=/etc/xinetd.d/discard-stream] [line=67]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration file: /etc/xinetd.d/echo-dgram [file=/etc/xinetd.d/echo-dgram] [line=67]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration file: /etc/xinetd.d/echo-stream [file=/etc/xinetd.d/echo-stream] [line=67]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration file: /etc/xinetd.d/ftp-sensor [file=/etc/xinetd.d/ftp-sensor] [line=67]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration file: /etc/xinetd.d/rsyncd [file=/etc/xinetd.d/rsyncd] [line=70]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration file: /etc/xinetd.d/tcpmux-server [file=/etc/xinetd.d/tcpmux-server] [line=10]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration file: /etc/xinetd.d/time-dgram [file=/etc/xinetd.d/time-dgram] [line=68]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration file: /etc/xinetd.d/time-stream [file=/etc/xinetd.d/time-stream] [line=67]
Jul  3 04:47:12 musltoo xinetd[2287]: removing chargen
Jul  3 04:47:12 musltoo xinetd[2287]: removing chargen
Jul  3 04:47:12 musltoo xinetd[2287]: removing daytime
Jul  3 04:47:12 musltoo xinetd[2287]: removing daytime
Jul  3 04:47:12 musltoo xinetd[2287]: removing discard
Jul  3 04:47:12 musltoo xinetd[2287]: removing discard
Jul  3 04:47:12 musltoo xinetd[2287]: removing echo
Jul  3 04:47:12 musltoo xinetd[2287]: removing echo
Jul  3 04:47:12 musltoo xinetd[2287]: removing ftp
Jul  3 04:47:12 musltoo xinetd[2287]: removing rsync
Jul  3 04:47:12 musltoo xinetd[2287]: removing tcpmux
Jul  3 04:47:12 musltoo xinetd[2287]: removing time
Jul  3 04:47:12 musltoo xinetd[2287]: removing time
Jul  3 04:47:12 musltoo xinetd[2287]: xinetd Version 2.3.15 started with libwrap loadavg options compiled in.
Jul  3 04:47:12 musltoo xinetd[2287]: Started working: 1 available service
Jul  3 04:47:12 musltoo sshd[2219]: Server listening with SCTP on 0.0.0.0 port 22.
Jul  3 04:47:12 musltoo sshd[2219]: Server listening with SCTP on :: port 22.
Jul  3 04:47:12 musltoo sshd[2219]: Server listening on 0.0.0.0 port 22.
Jul  3 04:47:12 musltoo sshd[2219]: Server listening on :: port 22.
Jul  3 04:47:12 musltoo vallumd[2244]: Connected to HIDDEN:8883
Jul  3 04:47:12 musltoo vallumd[2244]: Subscribed to topic blacklist4/#
Jul  3 04:47:12 musltoo vallumd[2244]: Subscribed to topic blacklist6/#
Jul  3 06:47:54 musltoo syslog-ng[1454]: Syslog connection established; fd='5', server='AF_INET6([HIDDEN]:5140)', local='AF_INET6([::]:0)'
Jul  3 04:48:18 musltoo sshd[2331]: Accepted publickey for root from HIDDEN port 54930 ssh2: ED25519 SHA256:HIDDEN
Jul  3 04:48:18 musltoo sshd[2331]: pam_unix(sshd:session): session opened for user root by (uid=0)
```

/etc/localtime has the correct timezone data:
```
musltoo ~ # diff /etc/localtime  /usr/share/zoneinfo/Europe/Berlin
musltoo ~ #
```

Configuring the [TZ environment variable](http://wiki.musl-libc.org/wiki/Environment_Variables#TZ) did not solve this problem. Verified in /proc/$PID/env of several programs that TZ was there. Tried both TZ=Europe/Berlin and TZ=/etc/localtime.

**Comment by bazsi** [comment]
Can you pls check what is exactly received by syslog-ng?

In debug mode syslog-ng logs this, but you can get the same info via strace.

On Jul 3, 2017 06:55, "Stijn Tintel" <notifications@github.com> wrote:

syslog-ng Version of syslog-ng

syslog-ng 3.10.1
Installer-Version: 3.10.1
Revision:
Module-Directory: /usr/lib/syslog-ng
Module-Path: /usr/lib/syslog-ng
Available-Modules:
snmptrapd-parser,stardate,map-value-pairs,add-contextual-data,cef,disk-buffer,kvformat,date,graphite,pseudofile,linux-kmsg-format,dbparser,afstomp,basicfuncs,cryptofuncs,confgen,system-source,affile,http,csvparser,afsocket,afprog,afuser,syslogformat
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on

Platform

Gentoo Hardened musl
Issue

When running syslog-ng on a system with musl libc, the timestamps in the
logs are incorrect. The kernel and syslog-ng log entries have the correct
timestamp (in the local timezone), but everything else seems to have
timestamps in UTC. This does not happen on a system with glibc and the
exact same syslog-ng configuration. A quick test with rsyslog on the same
musl system also did not show this behaviour.
Steps to reproduce

   1. start syslog-ng on a system with musl libc
   2. check timestamps in /var/log/messages

Configuration

/etc/syslog-ng/syslog-ng.conf:

@version: 3.10
#
# Syslog-ng default configuration file for Gentoo Linux

## https://bugs.gentoo.org/show_bug.cgi?id=426814
@include "scl.conf"

options {
        threaded(yes);
        chain_hostnames(no);

        # The default action of syslog-ng is to log a STATS line
        # to the file every 10 minutes.  That's pretty ugly after a while.
        # Change it to every 12 hours so you get a nice daily update of
        # how many messages syslog-ng missed (0).
        stats_freq(43200);
        # The default action of syslog-ng is to log a MARK line
        # to the file every 20 minutes.  That's seems high for most
        # people so turn it down to once an hour.  Set it to zero
        # if you don't want the functionality at all.
        mark_freq(3600);
};

source src { system(); internal(); };

destination messages { file("/var/log/messages"); };

# By default messages are logged to tty12...
destination console_all { file("/dev/tty12"); };
# ...if you intend to use /dev/console for programs like xconsole
# you can comment out the destination line above that references /dev/tty12
# and uncomment the line below.
#destination console_all { file("/dev/console"); };

log { source(src); destination(messages); };
log { source(src); destination(console_all); };

Input and output logs (if possible)

Jul  3 06:46:59 musltoo syslog-ng[1454]: syslog-ng starting up; version='3.10.1'
Jul  3 04:46:59 musltoo crond[1482]: (CRON) STARTUP (1.5.0)
Jul  3 04:46:59 musltoo crond[1482]: (CRON) INFO (RANDOM_DELAY will be
scaled with factor 98% if used.)
Jul  3 04:46:59 musltoo crond[1482]: (CRON) INFO (running with inotify support)
Jul  3 06:46:59 musltoo kernel: ip_set: protocol 6
Jul  3 06:46:59 musltoo kernel: ip_tables: (C) 2000-2006 Netfilter Core Team
Jul  3 06:46:59 musltoo kernel: nf_conntrack version 0.5.0 (65536
buckets, 262144 max)
Jul  3 04:47:04 musltoo /etc/init.d/net.eth1[1887]: config_eth1 not
specified; defaulting to DHCP
Jul  3 04:47:07 musltoo haveged[2017]: haveged starting up
Jul  3 04:47:07 musltoo haveged[2019]: haveged: ver: 1.9.1; arch: x86;
vend: GenuineIntel; build: (gcc 5.4.0 ITV); collect: 128K
Jul  3 04:47:07 musltoo haveged[2019]: haveged: cpu: (L4 VC); data:
32K (L2 L4 V); inst: 32K (L2 L4 V); idx: 21/40; sz: 31924/59119
Jul  3 04:47:07 musltoo haveged[2019]: haveged: tot tests(BA8): A:1/1
B:1/1 continuous tests(B):  last entropy estimate 8.00105
Jul  3 04:47:07 musltoo haveged[2019]: haveged: fills: 0, generated: 0
Jul  3 06:47:07 musltoo kernel: random: crng init done
Jul  3 04:47:10 musltoo /etc/init.d/mysql[2092]: You don't appear to
have the mysql database installed yet.
Jul  3 04:47:10 musltoo /etc/init.d/mysql[2093]: Please run `emerge
--config =dev-db/percona-server-5.6.36.82.0` to have this done...
Jul  3 04:47:10 musltoo /etc/init.d/mysql[2025]: ERROR: mysql failed to start
Jul  3 04:47:12 musltoo /etc/init.d/php-fpm[2158]: ERROR: php-fpm
failed to start
Jul  3 04:47:12 musltoo /etc/init.d/xinetd[2251]: /etc/init.d/xinetd
uses runscript, please convert to openrc-run.
Jul  3 06:47:12 musltoo kernel: sctp: Hash tables configured (bind 256/256)
Jul  3 06:47:12 musltoo kernel: alg: No test for __sha1-mb (__intel_sha1-mb)
Jul  3 06:47:12 musltoo kernel: alg: No test for __sha1-mb
(mcryptd(__intel_sha1-mb))
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration
file: /etc/xinetd.d/chargen-dgram [file=/etc/xinetd.conf] [line=49]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration
file: /etc/xinetd.d/chargen-stream [file=/etc/xinetd.d/chargen-stream]
[line=67]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration
file: /etc/xinetd.d/check_mk [file=/etc/xinetd.d/check_mk] [line=67]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration
file: /etc/xinetd.d/daytime-dgram [file=/etc/xinetd.d/daytime-dgram]
[line=52]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration
file: /etc/xinetd.d/daytime-stream [file=/etc/xinetd.d/daytime-stream]
[line=67]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration
file: /etc/xinetd.d/discard-dgram [file=/etc/xinetd.d/discard-dgram]
[line=67]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration
file: /etc/xinetd.d/discard-stream [file=/etc/xinetd.d/discard-stream]
[line=67]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration
file: /etc/xinetd.d/echo-dgram [file=/etc/xinetd.d/echo-dgram]
[line=67]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration
file: /etc/xinetd.d/echo-stream [file=/etc/xinetd.d/echo-stream]
[line=67]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration
file: /etc/xinetd.d/ftp-sensor [file=/etc/xinetd.d/ftp-sensor]
[line=67]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration
file: /etc/xinetd.d/rsyncd [file=/etc/xinetd.d/rsyncd] [line=70]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration
file: /etc/xinetd.d/tcpmux-server [file=/etc/xinetd.d/tcpmux-server]
[line=10]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration
file: /etc/xinetd.d/time-dgram [file=/etc/xinetd.d/time-dgram]
[line=68]
Jul  3 04:47:12 musltoo xinetd[2287]: Reading included configuration
file: /etc/xinetd.d/time-stream [file=/etc/xinetd.d/time-stream]
[line=67]
Jul  3 04:47:12 musltoo xinetd[2287]: removing chargen
Jul  3 04:47:12 musltoo xinetd[2287]: removing chargen
Jul  3 04:47:12 musltoo xinetd[2287]: removing daytime
Jul  3 04:47:12 musltoo xinetd[2287]: removing daytime
Jul  3 04:47:12 musltoo xinetd[2287]: removing discard
Jul  3 04:47:12 musltoo xinetd[2287]: removing discard
Jul  3 04:47:12 musltoo xinetd[2287]: removing echo
Jul  3 04:47:12 musltoo xinetd[2287]: removing echo
Jul  3 04:47:12 musltoo xinetd[2287]: removing ftp
Jul  3 04:47:12 musltoo xinetd[2287]: removing rsync
Jul  3 04:47:12 musltoo xinetd[2287]: removing tcpmux
Jul  3 04:47:12 musltoo xinetd[2287]: removing time
Jul  3 04:47:12 musltoo xinetd[2287]: removing time
Jul  3 04:47:12 musltoo xinetd[2287]: xinetd Version 2.3.15 started
with libwrap loadavg options compiled in.
Jul  3 04:47:12 musltoo xinetd[2287]: Started working: 1 available service
Jul  3 04:47:12 musltoo sshd[2219]: Server listening with SCTP on
0.0.0.0 port 22.
Jul  3 04:47:12 musltoo sshd[2219]: Server listening with SCTP on :: port 22.
Jul  3 04:47:12 musltoo sshd[2219]: Server listening on 0.0.0.0 port 22.
Jul  3 04:47:12 musltoo sshd[2219]: Server listening on :: port 22.
Jul  3 04:47:12 musltoo vallumd[2244]: Connected to HIDDEN:8883
Jul  3 04:47:12 musltoo vallumd[2244]: Subscribed to topic blacklist4/#
Jul  3 04:47:12 musltoo vallumd[2244]: Subscribed to topic blacklist6/#
Jul  3 06:47:54 musltoo syslog-ng[1454]: Syslog connection
established; fd='5', server='AF_INET6([HIDDEN]:5140)',
local='AF_INET6([::]:0)'
Jul  3 04:48:18 musltoo sshd[2331]: Accepted publickey for root from
HIDDEN port 54930 ssh2: ED25519 SHA256:HIDDEN
Jul  3 04:48:18 musltoo sshd[2331]: pam_unix(sshd:session): session
opened for user root by (uid=0)

/etc/localtime has the correct timezone data:

musltoo ~ # diff /etc/localtime  /usr/share/zoneinfo/Europe/Berlin
musltoo ~ #

Configuring the TZ environment variable
<http://wiki.musl-libc.org/wiki/Environment_Variables#TZ> did not solve
this problem. Verified in /proc/$PID/env of several programs that TZ was
there. Tried both TZ=Europe/Berlin and TZ=/etc/localtime.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/balabit/syslog-ng/issues/1581>, or mute the thread

**Comment by stintel** [comment]
```
[2017-07-03T09:50:01.690423] Incoming log entry; line='<78>Jul  3 07:50:01 crond[3660]: (root) CMD (test -x /usr/sbin/run-crons && /usr/sbin/run-crons)\x0a'
[2017-07-03T09:50:01.690467] Setting value; msg='0x555686e88b80', name='.unix.cmdline', value='/usr/sbin/CROND '
[2017-07-03T09:50:01.690476] Setting value; msg='0x555686e88b80', name='.unix.pid', value='3660'
[2017-07-03T09:50:01.690481] Setting value; msg='0x555686e88b80', name='.unix.uid', value='0'
[2017-07-03T09:50:01.690488] Setting value; msg='0x555686e88b80', name='.unix.gid', value='0'
[2017-07-03T09:50:01.690496] Setting value; msg='0x555686e88b80', name='HOST_FROM', value='musltoo'
[2017-07-03T09:50:01.690506] Setting value; msg='0x555686e88b80', name='HOST', value='musltoo'
[2017-07-03T09:50:01.690514] Setting value; msg='0x555686e88b80', name='SOURCE', value='src'
[2017-07-03T09:50:01.690524] Filter node evaluation result; msg='0x555686e88b80', result='match', type='!='
[2017-07-03T09:50:01.690531] Setting value; msg='0x555686e88b80', name='PID', value='3660'
[2017-07-03T09:50:01.690539] Rewrite expression evaluation result; value='PID', new_value='3660', rule='#anon-rewrite0', location='source confgen system:6:15'
[2017-07-03T09:50:01.690770] Outgoing message; message='Jul  3 07:50:01 musltoo crond[3660]: (root) CMD (test -x /usr/sbin/run-crons && /usr/sbin/run-crons)\x0a'
[2017-07-03T09:50:01.690804] Outgoing message; message='Jul  3 07:50:01 musltoo crond[3660]: (root) CMD (test -x /usr/sbin/run-crons && /usr/sbin/run-crons)\x0a'
[2017-07-03T09:50:01.690812] Outgoing message; message='<78>Jul  3 07:50:01 musltoo crond[3660]: (root) CMD (test -x /usr/sbin/run-crons && /usr/sbin/run-crons)\x0a'
```

**Comment by bazsi** [comment]
Hi,

So as it seems musl sends the timestamps in utc regardless of
/etc/localtime being set.

Processes might read localtime once at startup, so a restart might help.

Also, I think even unix-stream() supports the time-zone option where you
can override the timezone assumed in these timestamps.

With all this said, I dont think this is a bug in syslog-ng.

**Comment by wiktor-b** [comment]
I'm not sure if it's a bug in musl either:

    % echo $TZ
    
    % diff /etc/localtime /usr/share/zoneinfo/UTC
    % date
    Mon Jul  3 08:17:22 UTC 2017
    % TZ=Europe/Berlin date
    Mon Jul  3 10:17:27 CEST 2017
    % cp /usr/share/zoneinfo/Europe/Berlin /etc/localtime
    % date
    Mon Jul  3 10:17:48 CEST 2017
    % TZ=UTC date
    Mon Jul  3 08:17:52 UTC 2017

**Comment by bazsi** [comment]
The question is if musl's syslog() implementation uses the localtime
setting or not.

A google search revealed this:

http://musl.openwall.narkive.com/9wh8IIq0/syslog-always-sends-gmt-timestamps

But like I said, you can override this using the time-zone() option.

-- 
Bazsi

**Comment by stintel** [comment]
Ok, seems I can 'fix' with these 2 options:
```
recv-time-zone('UTC');
time-zone('Europe/Berlin');
```
