### ISSUE TITLE
GeoIP lookup for IPv6

### ISSUE THREAD

**Issue by johnlinp** [balabit/syslog-ng#1586]
I can config `syslog-ng` to look up GeoIP for IPv4 IPs successfully. However, when I changed the `database` option from `/usr/share/geoip/GeoLiteCity.dat` to `/usr/share/geoip/GeoLiteCityv6.dat`, I failed to look up IPv6 IPs.

I tried to use the GeoIP library APIs to lookup IPv6 IPs with the IPv6 database and it works. So the database itself should be fine.

I don't see any statement like "`geoip` parser only supports IPv4 and not IPv6" in the documentation. Does it support IPv6? If not, is any progress going on?

**Comment by furiel** [comment]
For now, geoip module does not work with ipv6. libgeoip uses different api calls to ipv4 and ipv6:
From GeoIPCity.h:

GEOIP_API GeoIPRecord * GeoIP_record_by_addr(GeoIP * gi, const char *addr);
GEOIP_API GeoIPRecord * GeoIP_record_by_name(GeoIP * gi, const char *host);
vs                                                    
GEOIP_API GeoIPRecord * GeoIP_record_by_addr_v6(GeoIP * gi, const char *addr);
GEOIP_API GeoIPRecord * GeoIP_record_by_name_v6(GeoIP * gi, const char *host);
but only the ipv4 version is used in the syslog-ng geoip module. Possibly this can be changed at the cost of deciding if an address is v4 or v6, then querying the appropriate database with with the appropriate functions.

Currently there is an ongoing development that plans to deprecate this geoip module in favour of a new geoip2 module in syslog-ng that depends on libmaxminddb instead of libgeoip. The libmaxminddb api does not branch on ipv4 or ipv6, so should work on all kind of addresses. You can track the progress on https://github.com/balabit/syslog-ng/pull/1578 if interested.

**Comment by presidento** [comment]
@fekete-robert can you update the documentation to mention that (the existing) geoip does not support ipv6?

**Comment by furiel** [comment]
@fekete-robert your documentation update is great for geoip template function. Could you do the same for the geoip parser as well?
