### ISSUE TITLE
Disk buffer options check confusing

### ISSUE THREAD

**Issue by shastah** [balabit/syslog-ng#1733]
I'm running 3.12.1. As soon as I add `mem-buf-size(8192)`  to a non-reliable disk buffer, syslog-ng yields at startup:
```
[2017-10-22T18:00:01.156512] WARNING: Non-reliable queue: the mem-buf-size parameter is omitted;
```

Same thing happens as soon as I add `mem-buf-length(1000)` to a reliable disk buffer:
```
[2017-10-22T18:00:01.156559] WARNING: Reliable queue: the mem-buf-length parameter is omitted;
```

If the warning messages are what the code is really supposed to test, then conditions in `disk_queue_options_check_plugin_settings()` are reversed:
```
void
disk_queue_options_check_plugin_settings(DiskQueueOptions *self)
{
  if (self->reliable)
    {
      if (self->mem_buf_length > 0)
        {
          msg_warning("WARNING: Reliable queue: the mem-buf-length parameter is omitted");
        }
    }
  else
    {
      if (self->mem_buf_size > 0)
        {
          msg_warning("WARNING: Non-reliable queue: the mem-buf-size parameter is omitted");
        }
    }
}
```
They are initalized to `-1` in `disk_queue_options_set_default_options()`, so shouldn't those be testing for less than zero?

And BTW, [OSE documentation](https://www.balabit.com/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/reference-destination-syslog-chapter.html) adds to the confusion:
* doc[1] says `mem-buf-length()` should be used "if the option `reliable()` is set to no"
* doc[1] says `mem-buf-size()` should be used "if the option `reliable()` is set to yes"

I believe this is contrary to what the plugin code does, because:
* code emits warning if "mem-buf-length parameter is omitted" for reliable=yes
* code emits warning if "mem-buf-size parameter is omitted" for reliable=no

So maybe it's the warning messages that are wrong, and they should say "NOT omitted"?

My syslog-ng version info:
```
syslog-ng 3 (3.12.1)
Installer-Version: 3.12.1
Revision: 
Module-Directory: /usr/lib64/syslog-ng
Module-Path: /usr/lib64/syslog-ng
Available-Modules: affile,graphite,map-value-pairs,afsql,http,kvformat,snmptrapd-parser,cryptofuncs,pseudofile,linux-kmsg-format,dbparser,stardate,tags-parser,basicfuncs,add-contextual-data,afprog,xml,afsocket,system-source,afstomp,confgen,csvparser,tfgetent,afmongodb,cef,disk-buffer,afuser,syslogformat,mod-python,date
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: on
Enable-Systemd: off
```

**Comment by furiel** [comment]
> They are initalized to -1 in disk_queue_options_set_default_options(), so shouldn't those be testing for less than zero?

No, because KW_MEM_BUF_LENGTH '(' nonnegative_integer ')' in the grammar denies any negative value. So if buffer length is negative, it means user did not specify it in the configuration. In that case 
```
if (self->options.mem_buf_length < 0)
    self->options.mem_buf_length = dd->log_fifo_size;
```
will set to the initial value in `diskq.c`

> If the warning messages are what the code is really supposed to test, then conditions in disk_queue_options_check_plugin_settings() are reversed [...]

Is it possible you misread emitted instead of omitted?
```WARNING: Reliable queue: the mem-buf-length parameter is omitted"```
I double checked the meaning of [omit](https://dictionary.cambridge.org/dictionary/english/omit), it means fail to include. This code is indeed emitted when mem_buf_length  > 0 (i.e. when users specified it in the config) and reliable == yes. This is an invalid configuration, so the code should ignore it: hence the omitted. So the warning aligns with the documentation.

**Comment by shastah** [comment]
Thanks for the explanation @furiel - maybe a better choice for the warning message would be to say "ignored" instead of "omitted" then? To me "to omit" sounds more like "X should be there, but it was (deliberately?) omitted", and not "it *shouldn't* be there, so it was omitted".

**Comment by furiel** [comment]
I agree ignored would be definitely better than omitted. Or even, my personal peference is that when I misconfigure something, I like to see some negative keywords like not, cannot. Or even going further, the warning could indicate a way to resolve the issue. Something like:
`WARNING: mem-buf-length is incompatible with reliable queue, thus mem-buf-length option is ignored. Did you mean: mem-buf-size?`

From my perspective I would not change this because the warning achieves what is intended: moves the focus of the reader towards  the problematic option, though it could be more direct in explaining what is the problem exactly. Nevertheless if you like to contribute to syslog-ng, feel free to create a pull request for this change. Approve from my side.

There is only one thing to consider: all error/warning/etc messages are part of the user interface, changing them could potentially include regression. Though in this specific case I think the risk is relatively low. I checked our test database, and we do not assert for these specific warning strings, so a pull request on changing these could come in clean.
