### ISSUE TITLE
Disk buffer for syslog/tcp destination driver loses messages

### ISSUE THREAD

**Issue by shastah** [balabit/syslog-ng#1734]
I'm assessing the reliability of disk-buffer when used with syslog destination driver with TCP protocol.

My testing scenario is quite simple:
* both client and server are running 3.12.1
* client:
```
@version: 3.12

options {
	flush_lines (0);
	time_reopen (10);
	log_fifo_size (10240);
	log_msg_size (8192);
	chain_hostnames (no);
	use_dns (no);
	use_fqdn (no);
	create_dirs (no);
	keep_hostname (yes);
	owner("root");
	group("root");
	perm(0640);
	stats_freq (0);
	check_hostname (yes);
	dns_cache (yes);
};

source s_system {
	unix-dgram("/dev/log");
	internal();
};

destination d_tcp_syslog {
  syslog("172.21.21.42"
         port(514)
         transport("tcp")
         disk-buffer(mem-buf-length(10000)
                     mem-buf-size(16M) disk-buf-size(16M)
                     reliable(yes) dir("/var/lib/syslog-ng")
         )
  );
};

log { source(s_system); destination(d_tcp_syslog); };
```
* server
```
@version: 3.12

options {
	flush_lines (0);
	time_reopen (10);
	log_fifo_size (10240);
	log_msg_size (8192);
	chain_hostnames (no);
	use_dns (no);
	use_fqdn (no);
	create_dirs (no);
	keep_hostname (yes);
	owner("root");
	group("root");
	perm(0640);
	stats_freq (0);
	check_hostname (yes);
	dns_cache (yes);
};

source s_network {
	syslog(port(514)
	       flags(no-multi-line)
	       log_iw_size(50000)
	);
};

destination d_sink { file("/var/log/hosts/$HOST-$R_YEAR-$R_MONTH.log"); };
log { source(s_network); destination(d_sink); };
```

I'm trying to simulate server's crash, so I'm doing:
1. On the client, log current date every second in a loop
```
$ while true; do 
    logger -p user.info -t test "test $(date "+%Y-%m-%d %H:%M:%S")";
    sleep 1;
done
```
2. Block all tcp/514 traffic (both incoming and outgoing) on the server (this simulates ungraceful shutdown of the machine)
3. Wait a couple of seconds (simulating server rebooting)
4. Restart syslog-ng on the server
5. Unblock traffic

In this test client only starts buffering messages once destination driver realizes it lost TCP connection (which is signaled in logs as `Syslog connection broken; fd='15', server='AF_INET(172.21.21.42:514)', time_reopen='10'`).

Sequence of events (with dates) on the server:
```
root@server:~# iptables -I INPUT -p tcp --dport 514 -j DROP; iptables -I OUTPUT -p tcp --sport 514 -j DROP; echo "traffic dropping since $(date)"
traffic dropping since Sun Oct 22 20:22:34 CEST 2017
root@server:~# /etc/rc.d/rc.syslog-ng stop
Stopping syslog-ng daemon
root@server:~# /etc/rc.d/rc.syslog-ng start
Starting syslog-ng daemon:  /usr/sbin/syslog-ng
root@server:~# iptables -D INPUT -p tcp --dport 514 -j DROP; iptables -D OUTPUT -p tcp --sport 514 -j DROP; echo "stop restored traffic at $(date)"
restored traffic at Sun Oct 22 20:23:09 CEST 2017
root@server:~# 
```

And this is what gets logged on the server:
```
Oct 22 20:22:31 client test: test 2017-10-22 20:22:30
Oct 22 20:22:32 client test: test 2017-10-22 20:22:32
Oct 22 20:22:33 client test: test 2017-10-22 20:22:33
Oct 22 20:22:34 client test: test 2017-10-22 20:22:34  <---- last received msg before traffic is blocked
[nothing happens here, traffic is restored at 20:23:09
 but the TCP connection is not valid anymore as it a new
 syslog-ng instance listening on tcp/514]
Oct 22 20:23:13 client test: test 2017-10-22 20:23:13
Oct 22 20:23:13 client syslog-ng[25712]: EOF occurred while idle; fd='15' <--- msgs start being queued
Oct 22 20:23:13 client syslog-ng[25712]: Syslog connection broken; fd='15', server='AF_INET(172.21.21.42:514)', time_reopen='10'
Oct 22 20:23:14 client test: test 2017-10-22 20:23:14
Oct 22 20:23:15 client test: test 2017-10-22 20:23:15
Oct 22 20:23:16 client test: test 2017-10-22 20:23:16
Oct 22 20:23:17 client test: test 2017-10-22 20:23:17
Oct 22 20:23:18 client test: test 2017-10-22 20:23:18
Oct 22 20:23:19 client test: test 2017-10-22 20:23:19
Oct 22 20:23:20 client test: test 2017-10-22 20:23:20
Oct 22 20:23:21 client test: test 2017-10-22 20:23:21
Oct 22 20:23:22 client test: test 2017-10-22 20:23:22
Oct 22 20:23:23 client syslog-ng[25712]: Syslog connection established; fd='15', server='AF_INET(172.21.21.42:514)', local='AF_INET(0.0.0.0:0)'
Oct 22 20:23:23 client test: test 2017-10-22 20:23:23
Oct 22 20:23:24 client test: test 2017-10-22 20:23:24
Oct 22 20:23:25 client test: test 2017-10-22 20:23:25
```

I kind of hoped syslog-ng with syslog/tcp destination would handle this kind of scenario, as it doesn't receive ACKs for those lost messages.

Is this a bug or a desired behaviour?

syslog-ng version is exactly the same on both client and server:
```
# syslog-ng --version
syslog-ng 3 (3.12.1)
Installer-Version: 3.12.1
Revision: 
Module-Directory: /usr/lib64/syslog-ng
Module-Path: /usr/lib64/syslog-ng
Available-Modules: affile,dbparser,graphite,csvparser,tfgetent,system-source,syslogformat,afsocket,afmongodb,snmptrapd-parser,disk-buffer,afuser,confgen,cryptofuncs,linux-kmsg-format,xml,tags-parser,pseudofile,stardate,afsql,afprog,date,mod-python,basicfuncs,afstomp,map-value-pairs,add-contextual-data,cef,http,kvformat
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: on
Enable-Systemd: off
```

**Comment by furiel** [comment]
@shastah very good analysis! Here are my thoughts:
In short: yes this is the expected behaviour. One cannot improve the reliability of a pure tcp driver any further in your scenario.

In details:
The diskbuffer mechanism for a general destination driver is the following: all messages that arrive to the client's destination driver are first written to disk, even before the destination driver tries to send the messages. The messages are then peeked from the destination queue before sending, but popped only if the underlying protocol of the destination driver reports back with success. So in practice, the buffering happens all the time for all messages, not only when there are problems with the connection.

Now in case of TCP driver, what syslog-ng does is it passes the message to the tcp stack of the kernel. Once the message is written to the local kernel buffers, kernel reports back with success, and from then it is the kernel's responsibility and authority to transport it correctly. So in summary, once syslog-ng writes the message the kernel buffer, the syscall will return with success, thus the message will be popped from the diskbuffer, not blocking until the tcp packets actually arrived and acknowledged on the remote stack.
> I kind of hoped syslog-ng with syslog/tcp destination would handle this kind of scenario, as it doesn't receive ACKs for those lost messages.

The problem is it is the kernel TCP stack who receives these acknowledgements, and these are not propagated back to user space. All that happens if kernel detects some problem with the connection, then the next socket write (handling the next message) will return with an error code, but that's late for the message stuck in the tcp kernel driver. Also there is the delayed acknowledgement mechanism in the tcp stack that controls how much packets can be sent before the receiving tcp stack must send back acknowledgement. Packet and acknowledgement is typically not a 1-1 packet relationship. 

A minor thought on the test scenario: the test scenario simulates essentially the crash of the machine of the remote server. However the diskbuffer on the local server intends to defend against failures of the local machine: in case of local crash, the messages are still available in the disk. It does not really add anything to remote failures compared to for example the default memory buffer instead of reliable diskbuffer: if the remote is not available, the messages are still buffered in the memory in the local machine. 
Although this is neither an entirely reliable even only for local failures in case of the tcp destination. In case of some very hard timing of a hardware power failure, it can still happen that a message can be lost, if syslog-ng already passed the message to the kernel buffer, but the power failure happens before the kernel buffers are flushed.

If one needs even more reliability, it can only be achieved with configuration change: some other protocol must be used over TCP to ensure proper application level acknowledgement mechanism. For example in syslog-ng premium edition there is the RLTP protocol over TCP: https://www.balabit.com/documents/syslog-ng-pe-6.0-guides/en/syslog-ng-pe-guide-admin/html/concepts-rltp.html
Or one can use http based destinations like http destination, kafka, elasticsearch when the http protocol ensures proper acknowledgement. Or one can write custom destination driver with syslog-ng's python or java binding, implementing any proprietary reliable protocol.
