### ISSUE TITLE
log message containing null character not forwarded correctly

### ISSUE THREAD

**Issue by erempel** [balabit/syslog-ng#1776]

**Comment by Kokan** [comment]
Hello,

This is currently a limitation that **syslog-ng** cuts the message at `\0` character.
This is due to that it is handled as a string, where the `\0` is the terminator of the array.

**Comment by erempel** [comment]
That is obviously not the case for all portions of syslog-ng because it is syslog-ng that is on the source machine and the file is written correctly at that locaiton.

**Comment by bazsi** [comment]
This depends a lot on the transport as well. Udp and rfc5424 with byte
counting would probably work.

But there are parts of the code base where it wouldn't work.

**Comment by erempel** [comment]
Isn't the ability to collect exact copies of logs to a central location a critical feature of a logging infrastructure? How would these logs be forwarded to a SIEM or central storage (Elastic Search)?

From my perspective this should be a high priority to get addressed. How many other log messages are "hidden" from view by poisoning the log message? This lowers my confidence in syslog-ng as a central component in my logging infrastructure.

**Comment by bazsi** [comment]
Most transports do not support embedded zeroes. Regexp libraries dont
support embedded zeroes. Syslog standards dont allow it.

For instance on tcp() zeroes are used for record termination just like
newlines.

Once a message is received that has zeroes in it, syslog-ng supports them
in some cases not in others, so if zeroes are critical, please test them
with your usecases.

You might need to change transports, in other cases these are easy to fix
issues, in other cases they difficult to fix issues.

It is always possible to replace NULs with a sequence right on input, but
that would change the message, but at least deliver it. It would also be a
performance hit, at least in some cases.


On Nov 26, 2017 10:07, "erempel" <notifications@github.com> wrote:

Isn't the ability to collect exact copies of logs to a central location a
critical feature of a logging infrastructure? How would these logs be
forwarded to a SIEM or central storage (Elastic Search)?

From my perspective this should be a high priority to get addressed. How
many other log messages are "hidden" from view by poisoning the log
message? This lowers my confidence in syslog-ng as a central component in
my logging infrastructure.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/balabit/syslog-ng/issues/1776#issuecomment-347027109>,
or mute the thread
