### ISSUE TITLE
Permission denied when accessing tomcat8 logfiles due to bad capabilities

### ISSUE THREAD

**Issue by Cytrian** [balabit/syslog-ng#1824]
## Version 
syslog-ng 3.9.1
Installer-Version: 3.9.1
Revision: 3.9.1-1
Module-Directory: /usr/lib/syslog-ng/3.9
Module-Path: /usr/lib/syslog-ng/3.9
Available-Modules: afsql,json-plugin,csvparser,linux-kmsg-format,confgen,afmongodb,basicfuncs,dbparser,syslogformat,sdjournal,afuser,date,pseudofile,disk-buffer,cef,cryptofuncs,afprog,affile,afsocket,system-source
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on

(also tried with 3.11.1)

## Platform
Debian Linux 9.1, Kernel 4.9.0

## Issue

Tomcat8 creates a log directory like this:
/var/log/tomcat8, owner 'tomcat8', group 'adm', permissions 'drwxr-x---', so no permissions for 'others'

When trying to open or stat any logfile within this directory, it is denied by the kernel, even though syslog-ng is running as user 'root', because 'others' are not allowed to access the file.

## Failure

After debugging this problem, I found out that the capabilities syslog-ng is setting are not sufficient to
open the files; the CAP_DAC_READ_SEARCH is missing or not effective.

These are the effective capabilities in the original configuration:
```
$ getpcaps 22168
Capabilities for '22168': = cap_syslog+ep cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_net_bind_service,cap_net_broadcast,cap_net_raw+p

$cat /proc/22168/status|grep Cap
CapInh: 0000000000000000
CapPrm: 0000000400002c0f
CapEff: 0000000400000000
CapBnd: 0000003fffffffff
CapAmb: 0000000000000000
```

After adding a custom ``--caps`` parameter when starting syslog-ng, it worked:

`--caps 'cap_dac_read_search,cap_syslog+ep           cap_chown,cap_dac_override,cap_dac_read_search,cap_syslog,cap_fowner,cap_net_bind_service,cap_net_broadcast,cap_net_raw+p'`

The effective capabilities are:
```
$ getpcaps 22196
Capabilities for `22196': = cap_dac_read_search,cap_syslog+ep cap_chown,cap_dac_override,cap_fowner,cap_net_bind_service,cap_net_broadcast,cap_net_raw+p

$ cat /proc/22196/status|grep Cap
CapInh: 0000000000000000
CapPrm: 0000000400002c0f
CapEff: 0000000400000004
CapBnd: 0000003fffffffff
CapAmb: 0000000000000000
```
```
$ capsh --decode=0000000400000004 
0x0000000400000004=cap_dac_read_search,cap_syslog
```

So, somehow it is not enought to have `cap_dac_read_search+p`, it is needed to  have `cap_dac_read_search+ep` to be able to access this directory.

**Comment by bazsi** [comment]
hi,

syslog-ng drops most its root capabilities at startup. You can disable this
behaviour using --no-caps as a command line option. Then it would be
running straight as root.

The default set of caps can be customized exactly for this reason, various
environment/configurations would have different requirements.

Once the initial startup is done, some of the capabilities are
automatically managed and are moved from the permitted to the effective set
at runtime. This code is not necessarily complete, and honestly I think we
would be better off if we just required stuff in "effective" and not adjust
capabilities at runtime. So your solution is as good as it gets.

btw: I was just checking when syslog-ng moves CAP_DAC_READ_SEARCH into
effective: it only happens with /proc/kmsg and not for anything else.

I wouldn't do this by default though, you might be running syslog-ng in
this constrained mode exactly because you don't want it to access certain
files/have access to certain parts of the system. If we were to override
CAP_DAC_READ_SEARCH by default for any file, that constrainment wouldn't
work.


-- 
Bazsi

**Comment by mochrul** [comment]
Maybe adding an option to the file source driver could solve this issue. And in this case, it only set the effective cap when deals with that file source.
