### ISSUE TITLE
wrong json format message with single quote

### ISSUE THREAD

**Issue by zjxlinux** [balabit/syslog-ng#2071]
# syslog-ng

When i am using syslog-ng and syslogng-kafka to push system logs to kafka Server. I notice that the messages are not json format,  messages use  single quote (which should be double-quotes ) and  can not be recognized and parsed by logstash 

## Version of syslog-ng

```
syslog-ng 3.7.3
Installer-Version: 3.7.3
Revision:
Compile-Date: Mar 23 2016 13:44:31
Available-Modules: pseudofile,confgen,system-source,linux-kmsg-format,csvparser,kvformat,afprog,affile,afuser,mod-python,afstomp,basicfuncs,syslogformat,afamqp,cryptofuncs,dbparser,graphite,afsocket,json-plugin
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
```

## Platform

CentOS release 6.8

reproduce
================
I use syslog-ng -F to debug and the logs be produced like this 
```bash
1 2018-05-30T13:57:14.721616+08:00 www.test.com syslogng_kafka 32288 - - Message produced: {'FACILITY': 'cron', 'PRIORITY': 'info', 'HOST': 'www.test.com', 'PROGRAM': 'CROND', 'DATE': '1527659821', 'MESSAGE': '(root) CMD (/usr/lib64/sa/sa1 1 1)'}
```

On logstash server i received the _jsonparsefailure error
![image](https://user-images.githubusercontent.com/16369233/40701951-7bba66da-6412-11e8-8478-a8b244dfc59b.png)

syslog-ng  conf 
```
source s_sys {
    file ("/proc/kmsg" program_override("kernel: "));
    unix-stream ("/dev/log" max-connections(512));
    internal();
};
destination syslog_to_kafka {
    python(
        class("syslogng_kafka.kafkadriver.KafkaDestination")
            on-error("fallback-to-string")
            options(
                hosts("xxx:9092")
                topic("system-log")
                verbose("True")
                display_stats("True")
                )
    );
};
log {
    source(s_sys);
    destination(syslog_to_kafka);
};
```

logstash conf 
```
input {
  kafka {
    bootstrap_servers => "xxxx:9092"
    topics => ["system-log"]
    codec => json
  }
}
......
```

**Comment by Kokan** [comment]
Just referencing this other issue here ilanddev/syslogng_kafka#18

**Comment by algernon** [comment]
The problem here is in the kafka destination you are using, linked [above](https://github.com/balabit/syslog-ng/issues/2071#issuecomment-393071345). It does *not* serialize to JSON, but to [Python string instead](https://github.com/ilanddev/syslogng_kafka/blob/52c06224a5860c427182d01359dc023bb178c213/syslogng_kafka/kafkadriver.py#L210).

There is nothing on the syslog-ng side we can do to fix it, you'll have to raise the issue there. As a workaround, you can fix your local copy of the destination, by adding an `import json` at the top, and replacing the linked line with this:

```python
msg_string = json.dumps(msg)
```

(syslog-ng also ships with a Kafka destination, that does not suffer from the same issue, but it requires Java, not Python, and has a different syntax too.)

**Comment by zjxlinux** [comment]
@algernon   highly appreciate your help, thanks.  It works for me.
