### ISSUE TITLE
compiling syslog-ng with python3

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#2090]
# syslog-ng

## Version of syslog-ng

syslog-ng git head from today

## Platform

openSUSE Leap 15.0

# Issue

```
[    5s] checking for python... no
[    5s] configure: error: Python interpreter is required
[    5s] error: Bad exit status from /var/tmp/rpm-tmp.9HbhpI (%build)
```
Configure fails, if **python**  binary is not available. That is the case on openSUSE Leap 15.0 and SLES, where only python3 is installed by default. The **python** binary is provided by the Python 2.7 package. If I symlink python to python3, compilation seems to work.
I have tried to use --with-python=python3 and --with-python=3.6, but neither of these resolved the problem.

**Comment by algernon** [comment]
> While I agree this should be fixed in autotools

No, this is not an autotools issue, it is a `configure.ac` issue, which can be fixed with reasonable ease.

```
AC_PATH_PROG(PYTHON, python)
```

This is what we do now. We explicitly tell autoconf to look for `python`. Because `AC_PATH_PROG` is a generic macro, it has no way of figuring out that we may want `python3` or `python3.5` or whatever. We can use `AM_PATH_PYTHON()` instead, which will do the right thing. We can also tell it to look for a minimum version, which is nice.

**Comment by algernon** [comment]
Mind you, we have a few places where we have `#!/usr/bin/env python` hardcoded, which we will need to change. Those parts should likely be configure-generated files instead, so it can substitute what it needs - though we'll need something similar for CMake too.

**Comment by czanik** [comment]
I expected --with-python to use the versioned binary, in case of --with-python=3.6 to use python3.6

cmake: for that I'd have to rewrite my spec file from the ground up (I only use packaged software). Is using cmake with syslog-ng documented anywhere? (but this is a different story)

**Comment by algernon** [comment]
I'll make it use a versioned binary when compiled with the appropriate `--with-python` option.
