### ISSUE TITLE
Syslog-ng loggen behavior

### ISSUE THREAD

**Issue by AiureaYO** [balabit/syslog-ng#2176]
Hello,

Here's the situation:

I have syslog-ng version 3.15. I've noticed that when using TLS and non-TLS transmission, the logs are different.

I have noticed that, when sending logs using the `loggen -i` (non-TLS, old RFC3164 format) command, I receive the following messages:

<pre>Jun 26 18:19:39 <strong>localhost</strong> prg00000[1234]: seq: 0000000000, thread: 0000, runid: 1530026379, stamp: 2018-06-26T18:19:39 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADD</pre> 

When using the `loggen -i -P` (non-TLS, newer RFC5424 format) command the messages look like this: 

<pre>Jun 26 18:19:28 <strong>192.168.1.10 256</strong> &lt;38&gt;1 2018-06-26T18:19:26+03:00 <strong>localhost</strong> prg00000 1234 - - &lt;U+FEFF&gt;seq: 0000000000, thread: 0000, runid: 1530026366, stamp: 2018-06-26T18:19:26 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPAD</pre>

When using the TLS `loggen -i -U` (TLS, old RFC3164 format) command it's not working: 

    [root@localhost ~]# loggen -i -U 192.168.1.7 6514
    Send error Connection reset by peer, results may be skewed.
    average rate = 606.59 msg/sec, count=7, time=0.011, (average) msg size=256, bandwidth=151.56 kB/sec

When using the TLS `loggen -i -P -U` (TLS, newer RFC5424 format) command the logs look like this: 

<pre>Jun 26 18:19:13 <strong>localhost</strong> prg00000[1234]: seq: 0000000000, thread: 0000, runid: 1530026353, stamp: 2018-06-26T18:19:13 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPAD</pre>

I know the $HOST macro uses the second column to split the logs by host. Having `localhost` in the second column when using TLS instead of the `IP-address` can be frustrating when switching between TLS and non-TLS. Can this situation be avoided somehow?

**Comment by gaborznagy** [comment]
Hi @AiureaYO!

Your issue is that most of the time you see `localhost` instead of the actual hostname right?

The line in which the `loggen -i -P (non-TLS, newer RFC5424 format)` is used seems to be a parsing error on the reciever side.
As you can see the message length "256" is included in the message and it received a new header.
```
Jun 26 18:19:28 192.168.1.10 256 <38>1 2018-06-26T18:19:26+03:00 localhost prg00000 1234 - - <U+FEFF>seq: 0000000000, thread: 0000, runid: 1530026366, stamp: 2018-06-26T18:19:26 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPAD
```

Can you share your syslog-ng configuration, please?

By the way I was able to reproduce the above parsing error, if I use `network()` source with `flag(syslog-protocol)` expecting an RFC 5424 message and using loggen with the `-i -P` options:
```
Jul  9 16:23:25 localhost 256 <38>1 2018-07-09T16:23:25+02:00 localhost prg00000 1234 - - ﻿seq: 0000000000, thread: 0000, runid: 1531146205, stamp: 2018-07-09T16:23:25 PADD
```

**Comment by AiureaYO** [comment]
Hi @gaborznagy ,

The problem is that when switching between the TCP and TLS transmision I get 2 different results. Meaning that I always expect an `IP-address` instead of `hostname`. `localhost` was my default hostname.

**Comment by AiureaYO** [comment]
Non-TLS config for the receiver
<pre>source "mhindp" { tcp(port(5514)); };

destination "vma0mj" { file("/opt/data/Test1NoTLS/$HOST/Test1NoTLS_1.log" dir_group(root) group(root) create_dirs(yes) dir_perm(0777) perm(0666) owner(root) dir_owner(root)); };

log { source("mhindp"); destination("vma0mj"); }; </pre> 

TLS config for the receiver 
<pre>source "s3cppj" { syslog( port(6514) transport("tls") tls(peer-verify(optional-untrusted) key-file("/etc/syslog/594ewh.key") cert-file("/etc/syslog/594ewh.crt")) ); };
destination "sma0d5" { file("/opt/data/Test2TLS/$HOST/Test2TLS_1.log" dir_group(root) group(root) create_dirs(yes) dir_perm(0777) perm(0666) owner(root) dir_owner(root)); };
log { source("s3cppj"); destination("sma0d5"); };
</pre>

**Comment by gaborznagy** [comment]
I think the problem is framing. syslog() driver in syslog-ng and loggen as well sends RFC5424 formatted messages with framing: **message length** + msg
E.g.
"**256** <13>1 2018-07-09T16:23:25+02:00 localhost ...."
tcp() or network() driver on the other hand does not expect framing, although it can parse RFC5424 formatted messages(when flags(syslog-protocol) option is used).

I guess you only see this problem, because you sent the syslog-protocol message with loggen to the tcp() driver (port 5514), am I right?
The syslog protocol through TLS was sent to the syslog() driver (port 6514), right?

**The solution is to disable framing in loggen (use the "-F" option of loggen) and use "flags(syslog-protocol)" option in your network() source:.**
```
$bin/loggen -n 1 -iPF localhost 1112
...
# On syslog-ng side output:
Jul 13 15:48:14 localhost prg00000[1234]: seq: 0000000000, thread: 0000, runid: 1531489694, stamp: 2018-07-13T15:48:14 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPAD
```
However this only solves your problem with loggen, if your log source sends its log messages with framing it will cause the same problem with your tcp() source driver.

What kind of message format do you expect on source `mhindp`?
Is it the newer RF5424 or the legacy syslog format RFC3164 or mixed?
Using `syslog()` source driver would handle (and expect!) framing from loggen or syslog().

Btw let me inform you, that the tcp(), upd() drivers are obsolete and it is recommended to use the newer network() driver.
See our [documentation](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.16/administration-guide/25#TOPIC-962276).

**Comment by AiureaYO** [comment]
@gaborznagy  Thank you very much for your incredible help! Your understanding was 100% correct. This was exactly what I was looking for. Thank you so much for the detailed framing explanation!

**Comment by gaborznagy** [comment]
You're welcome!
