### ISSUE TITLE
Enhancement: Riemann: add tags() from ${TAGS}

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#226]
I was thinking of a way to have all events tagged naturally using their `${TAGS}` macro, but the following doesn't obviously do as intended:

```
tags("$(replace-delimiter \",\" \" \" \"${TAGS}\")")
```

How could this be done in a sane way?

**Comment by szemere** [comment]
Dear @faxm0dem ,
 we were looking into this old issue. We discussed the possibility of supporting templates inside tags. Since no one else mentioned/requested this feature, and nobody took the chance to implement it in the past years, I think it is not feasible way.
 However I would like to deeper understand your problem and find other ways to solve it.

1. mimic `attribute(foo => bar)` with `tag(foo.bar)`
To be honest I do not clearly understand this (in reflection to the provided `replace-delimeter` example). Would you like to put every attribute into one big `tag`, or group them into "pairs by attributes"?

2. Exactly how did you mean "so I can workaround this"? It is possible to provide `tags` to Riemann in some other way? Does the limitation still exists in Riemann?

Br,
Laci

**Comment by faxm0dem** [comment]
the Riemann limitation I was mentioning is no longer present, so the original use-case is defeated.
However, it would seem natural that the riemann destination would pick up the $TAGS macro as riemann tags, don't you think?

**Comment by faxm0dem** [comment]
thanks so much for the test and clarification! si the missing piece is just that `set-tag` is not templateable. this could justify a separate issue, but as I don't need it anymore, I leave it up to you to open it if you feel it necessary!

you can close this issue then

thanks for being so thorough on old issues!
