### ISSUE TITLE
Having issues viewing the Log File Name in Kibana

### ISSUE THREAD

**Issue by JawadKM** [balabit/syslog-ng#2309]
Hi,
I am using syslog-ng to push logs to elasticsearch and view in Kibana.
Problem I am facing right now is that, I can view all the logs in Kibana but I cannot I identify which log file they belong to. In my case same log is recorded in more than one log file.
Below is the example of the config in syslog-ng **"source and destination of my log file"**

source s_apache{
    file("/opt/int/apache/logs/cat.log");
    };

destination d_syslog_tcp {

syslog("192.*.*.*" transport("tcp") port(514)); };

log { source(s_apache); destination(d_syslog_tcp); };

So, in Kibana it will show me the log line but would not tell that this log line is taken from file **cat.log**

Any help in this regard will be highly appreciated.

**Comment by Kokan** [comment]
You have to transport the filename also, because that is I think now lost. The macro you could use `FILE_NAME`, in the relay this stores the name of the file.


One of the way is to use the `ewmm`, which sends all of the macros, you can just specify instead of `syslog("192..." transport("tcp") port(514));` the `ewmm(ip("192...") transport("tcp") port(514));`.
On the source side the same could be used.

Note: it has some performance penalty.

**Comment by JawadKM** [comment]
@Kokan do you mean to configure it this way?

source s_apache (filename("cat.log") ) {
file("/opt/int/apache/logs/cat.log");
};

**Comment by Kokan** [comment]
The `ewmm` is a new feature you need at least `3.17.2` (so pretty bleeding edge).

I assumed you have syslog-ng as relays collecting from log files sending to a server syslog-ng that forwards all of the messages to elasticsearch.
And based on that your relays do not send the file name to the server, so the server cannot send it towards elasticsearch.

If this is a case you have to make sure to transfer the file name information from relay to server. The before mentioned destination (`ewmm`) sends all of the macro to the server. (Like `FILE_NAME`, which has the file path it read the message from). The `ewmm` source could recieve it, and you should have your file name in elasticsearch.

About the config error: please see my example abow (the ip must be in an `ip` block: `ewmm(ip(...) ...)`.

**Comment by bazsi** [comment]
just a note, that if you send messages between syslog-ng hops (e.g. from a
syslog-ng client to a syslog-ng server), and you want to transfer ALL
name-value pairs, then the preferred form of sending logs from one to the
next is to use the syslog-ng() driver, and not the ewmm() one.

On the server side, you can decode these messages using the
default-network-drivers() source that registers all parsing rules that make
ewmm work out of the box, OR you could also use the ewmm() source, but that
on a dedicated port.

The default-network-drivers() sources allow the intermixing of legacy
syslog messages and this new name-value format and will properly handle
both.

One you have all name-value pairs, FILE_NAME would be available on the
server to send it on to elasticsearch. Basically it's pretty easy to
include that information in that payload, though you might have to override
the default template as that does not include FILE_NAME.

Here are the minimal examples for this usecase (untested):

client.conf
```
@version: 3.17
@include 'scl.conf'
log {
    source { system(); };
    destination { syslog-ng(server("ip-address-of-the-server")); };
};
```
server.conf
```
@version: 3.17
@include 'scl.conf'
log {
    source { default-network-drivers(); };
    # at this point ewmm is automatically parsed by
default-network-drivers()
    destination { elasticsearch2(...template("$(format-json --all-nv-pairs
--exclude DATE --key ISODATE @timestamp=${ISODATE})") ...) };
};
```
Basically the flow of processing would be like this:

   - the client gets messages from the local transport, where it has the
   ability to automatically parse local log messages (e.g. iptables logs are
   automatically parsed into name-value pairs, but $FILE_NAME is filled in
   case it is read from a file)
   - the client sends these messages to the server in "rich" mode, e.g. all
   name-value pairs, tags() and everything is transferred
   - the server used default-network-drivers() that opens _ALL_ applicable
   syslog transports by default
   - default-network-drivers() couples the sources with automatic parsing
   that processes the rich format the client is sending (e.g. ewmm)
   - in this way, the server will have access to all name-value pairs that
   the client extracted
   - then the server uses the elasticsearch2() destination and customize it
   to send all name-value pairs automatically.
   - kibana has access to FILE_NAME
   - happyness :)

In order to add more automatic parsing to the mix, we only need to add new
application adapters, the iptables one is here:
https://github.com/balabit/syslog-ng/blob/master/scl/iptables/iptables.conf

Bazsi

**Comment by JawadKM** [comment]
@Kokan @bazsi  I have my Dev environment up and running thanks to you guys.
I might be requesting some help again when every thing goes in Prod.
