### ISSUE TITLE
elasticsearch maven repository need to be fix

### ISSUE THREAD

**Issue by ben956** [balabit/syslog-ng#2390]
version: syslog-ng-3.13.2
I could not make and fail with below msg:
----------
syslog-ng Could not get resource 'http://maven.elasticsearch.org/releases/org/elasticsearch/plugin/shield/2.4.0/shield-2.4.0.pom'
----------

elasticsearch maven repository need to be fix
its location is \syslog-ng\modules\java-modules\build.gradle

line 19 needs to be changed as below:
url "https://artifacts.elastic.co/maven"

I don't have access to push :(

**Comment by Kokan** [comment]
@ben956 you could always fork and create a PR. (the way we do it, we are not pushing to the repo but merging).

I am not that familiar with the elastic maven repository, has the location of the elasticsearch maven repository changed ?

ps: The `syslog-ng-3.13.2` tag is set in stone, no way anybody can change that, it would be possible to release a `3.13.3` version, but we usually only integrate into master and the fix is released in the next release.

**Comment by szemere** [comment]
Dear @ben956,
 I finally figured out all the threads in this topic.

 In #1895 we dropped the shield module support from syslog-ng.
 In PR #2409 I deliberately created two commits. The first only updates the third party repository URL. Using that commit, and the one from the referenced PR, you can build a local version of syslog-ng reenabling the shield module.

 For the reference: We missed this 3rd party repository issue in our nightly build because gradle evaluates package sources in the order of declaration.
 Without shield support, we can download every package from `mavenCentral` , so the 3rd party URL became obsolete, and gradle never tried to reach it.

Br,
Laci
