### ISSUE TITLE
Source and log ordering affect tag ordering

### ISSUE THREAD

**Issue by danbeaulieu** [balabit/syslog-ng#2431]
# syslog-ng

## Version of syslog-ng

```
$ sudo syslog-ng --version
syslog-ng 3 (3.18.1)
Config version: 3.18
Installer-Version: 3.18.1
Revision: 
Compile-Date: Nov 26 2018 20:49:32
Module-Directory: /usr/local/lib/syslog-ng
Module-Path: /usr/local/lib/syslog-ng
Include-Path: /usr/local/share/syslog-ng/include
Error opening plugin module; module='mod-java', error='libjvm.so: cannot open shared object file: No such file or directory'
Available-Modules: dbparser,afprog,stardate,add-contextual-data,json-plugin,appmodel,system-source,cef,syslogformat,sdjournal,tfgetent,http,pseudofile,afsocket,afstomp,kvformat,hook-commands,disk-buffer,afuser,xml,confgen,graphite,map-value-pairs,linux-kmsg-format,tags-parser,csvparser,snmptrapd-parser,cryptofuncs,examples,affile,date,mod-python,basicfuncs
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: off
Enable-Linux-Caps: on
Enable-Systemd: off
```

## Platform

Ubuntu 16.04

## Debug bundle

Create a debug bundle on your system with the syslog-ng-debun script which is included in the syslog-ng package.

Overwiew of the CLI options of syslog-ng-debun:
-r: run actual information gathering
-d: run syslog-ng in debug mode
-p: perform packet capture
-s: do strace
-t: timeout period for running debug/pcap/strace
-w: wait period before starting debug mode
-l: light information gathering (respects privacy)
-R: alternate installation directory for syslog-ng

```
$ syslog-ng-debun -r
```

# Issue

## Failure

If the syslog-ng conf has multiple sources that set tags() the tags are reordered after the first source.

## Steps to reproduce

1. start syslog-ng

## Configuration

```
@version: 3.18
@include "scl.conf"

source s_local {
  internal();
};

source s_network {
 default-network-drivers(
    # NOTE: TLS support
    #
    # the default-network-drivers() source driver opens the TLS
    # enabled ports as well, however without an actual key/cert
    # pair they will not operate and syslog-ng would display a
    # warning at startup.
    #
    #tls(key-file("/path/to/ssl-private-key") cert-file("/path/to/ssl-cert"))
  );
};

destination d_local {
  file("/var/log/messages");
  file("/var/log/messages-kv.log" template("$ISODATE $HOST $(format-welf --scope all-nv-pairs)\n") frac-digits(3));
};

log {
  source(s_local);
  source(s_network);
  destination(d_local);
};

@define cloud_en "dev"
@define cloud_stack "nightly"
@define NODE_NAME "node-a"

options {
  stats_freq (0);
  flush_lines (0);
  time_reopen (10);
  chain_hostnames (off);
  use_dns (no);
  use_fqdn (no);
  create_dirs (no);
};

source 'log_file_a' {
file('/tmp/app-a.log'
 flags(no-parse, empty-lines)
 tags("`cloud_en`","app-a","`NODE_NAME`","`cloud_stack`","app-a-log")
 follow-freq(10)
 log_iw_size(100000)
);};

log {
  source ('log_file_a');
  rewrite(r_addtags);
  destination(d_syslog_net);
  flags(flow-control);
};

source 'log_file_b' {
  file('/tmp/app-b.log'
    flags(no-parse, empty-lines)
    tags("`cloud_en`","app-b","`NODE_NAME`","`cloud_stack`","app-b-log")
    follow-freq(10)
    log_iw_size(100000)
);};

log {
  source ('log_file_b');
  rewrite(r_addtags);
  destination(d_syslog_net);
  flags(flow-control);
};

destination d_syslog_net {
  syslog("tcp-receiver-host" transport("tcp")); };

rewrite r_addtags {
  set(
    "$TAGS",
    value(".SDATA.meta@18372.4.tags")
    );
};

```

(or gist URL)

## Input and output logs
Running with the above config as is, note the tag order where all of the interpolated variable values are pushed to the front for app-b

```
Outgoing message; message='2018-11-26T21:38:00.000-05:00 127.0.0.1 .SDATA.meta@18372.4.tags=dev,app-a,node-a,nightly,k8s-app-a,.source.log_file_a HOST=127.0.0.1 HOST_FROM=127.0.0.1 MESSAGE=2 SOURCE=s_network\x0a'
Outgoing message; message='2018-11-26T21:38:20.000-05:00 127.0.0.1 .SDATA.meta@18372.4.tags=dev,node-a,nightly,app-b,k8s-app-b,.source.log_file_b HOST=127.0.0.1 HOST_FROM=127.0.0.1 MESSAGE=3 SOURCE=s_network\x0a'

```

Commenting out the source and log for app-a produces tags in the specified order:

```
Outgoing message; message='2018-11-26T21:43:54.000-05:00 127.0.0.1 .SDATA.meta@18372.4.tags=dev,app-b,node-a,nightly,k8s-app-b,.source.log_file_b HOST=127.0.0.1 HOST_FROM=127.0.0.1 MESSAGE=3 SOURCE=s_network\x0a'
```
It's unclear if this is a bug or if behaving as designed but it is definitely unexpected behavior.

**Comment by szemere** [comment]
Hello @danbeaulieu ,

> If the syslog-ng conf has multiple sources that set tags() the tags are reordered after the first source.

 for performance reasons we do not handle the `tags` inside syslog-ng as `string`s, rather than that we assign `ID`s to them in the order of appearance and only replace them back in the final step, when we format the outgoing message.
 So the reordering in your case happens because some of the `tags` in the second source are "already exists", and the new ones get to the end of the current list.

 A possible solution would be to introduce some kind of ordering between the tags, but IMHO it will be always unfair/uncomfortable for someone. But suggestions are welcome! If you have an idea in the topic, feel free to share it with us!

 Because of this rather than changing syslog-ng's behaviour, I would focus on giving a workaround for your specific use case. My assumption is that you only shared the relevant part of your config, because:
The current destination do not contains any template or formatting, but the copied output is in "$(format-welf)" format.
So my workaround might be not suitable for you, and we have to further refine your needs.

Assuming you only want to asssign static SDATA elements to your message:

With [channel](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.18/administration-guide/14#TOPIC-1043930https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.18/administration-guide/14#TOPIC-1043930)s you can apply a rewrite rule on your source. For convenience reasons you can pack this all together into a [block](https://www.syslog-ng.com/community/b/blog/posts/creating-your-first-block-for-the-syslog-ng-configuration-library-scl) and create a new source type. i.e:


```
block source sdata-tagging-file-source(filename("") sdata-tags("") ...) {
    channel {
        source {
            file(`filename`
                `__VARARGS__`
            );
        };
        
        rewrite {
            set(`sdata-tags`, value(".SDATA.meta@18372.4.tags"));
        };
    }
};
```

usage:

```
source s_file1 {
    sdata-tagging-file-source(
        filename("/source/input.log")
        flags(no-parse)
        sdata-tags("a,1,c")
        follow-freq(10)
    );
};
```

some notes:
 - Sorry for the long names, but I wanted to make clear which part you can modify, and which part is a built in keyword.
 - The file source has a non optional unnamed option, the filename itself. I have to give a name to this, but all the other options are untuched and can be used freely, thanks to `__VARARGS__` 

Br,
Laci

**Comment by alltilla** [comment]
@danbeaulieu:

Hi Dan,
Is this workaround suitable for you? Do you have any more questions?
We are happy to help. :)

Best regards,
Attila

**Comment by Kokan** [comment]
If somebody faces this issue please consider that `tags` are unordered; but the above mentioned workaround could help.
