### ISSUE TITLE
Error binding socket; addr='AF_INET(0.0.0.0:6508)', error='Address already in use (98)'

### ISSUE THREAD

**Issue by mohankhanna** [balabit/syslog-ng#2448]
# syslog-ng

Error binding socket; addr='AF_INET(0.0.0.0:6508)', error='Address already in use (98)'
## Version of syslog-ng

```
syslog-ng 3.5.6
Installer-Version: 3.5.6

```

## Platform

RedHat 7

## Debug bundle

$ syslog-ng-debun -r
```

# Issue
Hi,
I am getting following error.
/usr/sbin/syslog-ng -Fdev -p /var/run/syslogd.pid
..
.
.
Module loaded and initialized successfully; module='syslogformat'
Module loaded and initialized successfully; module='linux-kmsg-format'
Error binding socket; addr='AF_INET(0.0.0.0:6508)', error='Address already in use (98)'

I can see syslog-ng is not running twice.
I tried stoping and starting it (even rebooting server) but that doenst resolve the problem.

I can see port in output of 'netstat -tunap|grep 6508'
netstat -tunap|grep 6508
tcp        0      0 0.0.0.0:6508            0.0.0.0:*               LISTEN      1677/syslog-ng

I can see syslog-ng is running but I its not logging any data to files locally
systemctl status  syslog-ng.service
● syslog-ng.service - System Logger Daemon
   Loaded: loaded (/usr/lib/systemd/system/syslog-ng.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-12-04 16:41:51 GMT; 11min ago
     Docs: man:syslog-ng(8)
 Main PID: 1677 (syslog-ng)
   CGroup: /system.slice/syslog-ng.service
           └─1677 /usr/sbin/syslog-ng -F -p /var/run/syslogd.pid

Dec 04 16:41:51 FB1PLOGFR03 systemd[1]: Starting System Logger Daemon...
Dec 04 16:41:51 FB1PLOGFR03 systemd[1]: Started System Logger Daemon.



## Failure



```
$ gdb syslog-ng
 run
```

## Steps to reproduce

1. start syslog-ng

2. ...

## Configuration

```
[root@FB1PLOGFR03 syslog-ng]# cat /etc/syslog-ng/syslog-ng.conf

@version:3.5
@include "scl.conf"

options {
    flush_lines (0);
    time_reopen (10);
    log_fifo_size (1000);
    chain_hostnames (off);
    use_dns (no);
    use_fqdn (no);
    create_dirs (yes);
    keep_hostname (yes);
    perm (0644);
    dir_perm (0700);
    owner (root);
    group (sys);
};
source s_sys {
    system();
#    internal();
    udp(ip(0.0.0.0) port(514));
    tcp(ip(0.0.0.0) port(514));
};
#
source s_ABC { udp(ip(0.0.0.0) port(6508)); };
source s_XYZ { udp(ip(0.0.0.0) port(6509)); };
#
rewrite r_7750_3PE {set("7750_3PE,$MESSAGE", value("MESSAGE")); };
rewrite r_7750_3PEa {set("7750_3PEa,$MESSAGE", value("MESSAGE")); };
#
destination d_FWRMGR1 { tcp("198.19.6.5" port(514)); };
destination d_LocalLog { file("/syslog-ng/$HOST"); };

log {source(s_ABC); rewrite(r_7750_3PE); destination(d_FBLOGMGR1); destination(d_LocalLog); flags(final);  };
log {source(s_XYZ); rewrite(r_7750_3PEa); destination(d_FBLOGMGR1); destination(d_LocalLog); flags(final);  };
# Source additional configuration files (.conf extension only)
@include "/etc/syslog-ng/conf.d/*.conf"
# vim:ft=syslog-ng:ai:si:ts=4:sw=4:et:

```

(or gist URL)

## Input and output logs (if possible)

**Comment by szemere** [comment]
Dear @mohankhanna,
 **IF***  I understand your scenario correctly, you have a syslog-ng - installed as a service - up and running. And you are trying to run a second instance of syslog-ng (for testing purposes?) in front with the `/usr/sbin/syslog-ng -Fdev -p /var/run/syslogd.pid` command.
 If this is the case, than the problem is that the second syslog-ng instance will load the same config as the already running one from the default location, and this is causing the "Address already in use (98)" error message.

 Running syslog-ng in front with the `-Fdev` options is a good practice, and makes the first steps much easier, but if you installed syslog-ng from a package, you must stop the service first with systemctl.


\* I emphasized if, because there are parts in your description which I do not clearly understand. Maybe you can try to delete the unused parts from the template, and use the code blocks in the markup language. Thank You!

Br,
Laci

**Comment by mohankhanna** [comment]
Thanks Laci, I appreciate you helping me here.
yes, My bad, I thought I was only checking errors with this command. but as you explained, its a second session. I should have known..
the reason I was trying this, because the data I am receiving on port 6508 in above config is not being written in the log file locally. I can see the udp data in the output of tcpdump. 

09:36:43.823326 IP (tos 0x0, ttl 53, id 34410, offset 0, flags [none], proto UDP (17), length 225)
    172.17.160.36.syslog > FB1PLOGFR03.6508: SYSLOG, length: 197
        Facility local0 (16), Severity info (6)
        Msg: Dec  5 09:36:47 filterlog: 45,,,1000011063,vtnet1.101,match,pass,out,4,0x0,,127,15874,0,DF,6,tcp,52,192.168.201.119,172.17.50.186,1515,8834,0,S,1094767377,,64240,,mss;nop;wscale;nop;nop;sackOK

Any idea.

**Comment by szemere** [comment]
Hello,
 as I sad, checking errors by running syslog-ng in front is a good practice, keep it up during integration/testing!
 About "data not being written in the log file": first, I would make sure, syslog-ng is indeed receiving those packets. (i.e.: UDP packets are usually visible in tcpdump, even if the application do not gets them because of some firewall rules.) You can verify this in two ways:
- Investigate the debug messages when you are running syslog-ng in front. You should see something like: `Incoming log entry; line='barfoo\x0a' on each incoming message.
- With the following netcat command you can listen manually on the mentioned port (make sure syslog-ng is not running) and verify if your firewall indeed forwards those packets: `netcat -ulp <port number>`

If these methods do not help, you can temporarily add a new source to your configuration (i.e file source) and test log writing with that.

Br,
Laci

**Comment by mohankhanna** [comment]
Thanks Laci,
I am trying to run it in degug mode but it just doesn't do anything after following line. 
syslog-ng starting up; version='3.5.6'
I can see loads of data on port 6554 in tcpdump output but I cant see it being processed in degug mode.
in tcpdump data looks something like this
13:33:14.760947 IP (tos 0x0, ttl 53, id 35277, offset 0, flags [none], proto UDP (17), length 225)
    172.17.160.36.syslog > syslog_server.6554: SYSLOG, length: 197
        Facility local0 (16), Severity info (6)
        Msg: Dec  5 13:33:15 filterlog: 45,,,1000011063,vtnet1.101,match,pass,out,4,0x0,,127,10791,0,DF,6,tcp,52,192.168.201.125,172.17.144.30,49479,9202,0,S,907335655,,64240,,mss;nop;wscale;nop;nop;sackOK

I have created very simple config now and its not even processing it.
here are entries of it (- global setting).
source s_sys {
    system();
    internal();
    udp(ip(0.0.0.0) port(514));
#    tcp(ip(0.0.0.0) port(514));
};
destination d_LocalLog { file("/syslog-ng/$SOURCEIP-$DAY.$MONTH.$YEAR"); };
filter f_TEST   { host ("172.17.160.36"); };
log { source(s_sys); filter(f_TEST); destination(d_LocalLog); flags(final); };

**Comment by mohankhanna** [comment]
the server also has 2 interfaces (mgmt. and service). can that cause problem?

**Comment by szemere** [comment]
>  but it just doesn't do anything after following line.

Somehow we should really make sure that your firewall actually passes those packets to syslog-ng. My asumption is that your current problem is not syslog-ng related. Syslog-ng simply do not get any data.

> the server also has 2 interfaces (mgmt. and service). can that cause problem?

By default syslog-ng will bind to the `0.0.0.0` ip address. (You don't have to provide it in your configuration.) The optional `ip` option is mostly there for "restricting" syslog-ng to one of your interface, in case you don't want to listen on both of them.

**Comment by mohankhanna** [comment]
Thanks for all the help.
