### ISSUE TITLE
Relax requirement on Python

### ISSUE THREAD

**Issue by patrickdepinguin** [balabit/syslog-ng#2463]
# syslog-ng

## Version of syslog-ng

3.18.1

## Platform

Linux

# Issue

Since syslog-ng 3.13.1, Python has become a requirement, checked by the configure script. The commit that introduced it (d1366df40dd6f00734a46132a94a9a741fe6a580) has the following comment: "It is used for testing and preprocessing grammar rules."

Is it correct that this requirement only really pertains to building syslog-ng, and not to running it?

In embedded systems with space limitations, Python is a too-heavy requirement. The interpreter along with its libraries take up many megabytes of space. For such systems, the compilation takes place on a desktop/server where Python can be reasonably expected (the host), but syslog-ng itself is run on the target where Python is not present.

Assuming the initial assumption is correct, the --with-python and similar options serve a dual purpose: it is used to point to both the Python needed at build-time, as to the Python optionally used at run-time (e.g. for custom Python sources and destinations).
On standard desktop or servers, there is no distinction, but on embedded systems there is.
To allow using syslog-ng on embedded systems without Python, the configure script should thus have additional options. For example:
--enable-python / disable-python
--with-python / without-python
These pre-existing options would specify the Python used at runtime. This Python is not required, and '--disable-python' is a valid choice.
--with-build-python
This option would specify the Python used at build time. As this Python is mandatory, there is no --disable-build-python.

To simplify configuration for non-embedded systems, there could be a rule that if no --with-build-python is specified, that it defaults to the value given in --with-python, and otherwise the automatically detected Python.

What are your thoughts on this?

**Comment by Kokan** [comment]
I think this is related #2179

**Comment by patrickdepinguin** [comment]
In some way it is related, but the statement there was: 
https://github.com/balabit/syslog-ng/issues/2179#issuecomment-404139922

> Yeah, it did, and my point is that doing so was a bug, because we [required a python interpreter](https://github.com/balabit/syslog-ng/blob/syslog-ng-3.15.1/configure.ac#L397) anyway.

And the point of this issue is precisely to only require a python interpreter for building, not for running.

**Comment by furiel** [comment]
@patrickdepinguin python is not a runtime dependency, it is a build dependency, unless one wants to use the python binding (`--enable-python/--disable-python`).

Afaik the python interpreter is needed only for generating the grammar files, or updating them when the templates change. (And for functional testing and python module code quality checks.)

For this latter we included the python detection into configure, though I believe that can be relaxed. Technically, if someone does not plan to edit the grammar templates and does not want to run the functional tests, and work from tarball instead of git clone (when the grammar files are already generated), there is no need for python even for building.

The detection might be changed to optional, and we could add to the `%.y: %.ym` rule a check if the python binary is detected, and then signal an error during the build, similar way we do with criterion: we can still configure without criterion, but signal error when running tests.

But from embedded point of view, this is probably not interesting. The cross compiled binary built on a  build machine with python should work without python on the embedded system.

If it is difficult to install python to your build machine, you can try to comment out `AC_MSG_ERROR([Python interpreter is required])` in `configure.ac` on any linux machine with python, call `autogen.sh`, create the tarball using `make dist`, move the tarball to the build machine, and continue from that.

To ease the first part, you can even use the dbld feature set in syslog-ng, if you have docker installed: edit configure.ac as before: then run `$ dbld/rules tarball`. That will pull a docker build environment for you, and prepares the tarball into `dbld/build`.

**Comment by patrickdepinguin** [comment]
@furiel Thanks for your response.
Having python installed on the build machine is according to me a realistic requirement, even for embedded development. So I think the last two paragraphs of your response are not needed.

But I'm puzzled by your paragraph "But from embedded point of view, this is probably not interesting.". While I did not check the code, your suggestion regarding changing the required python check in configure.ac, to a python binary check in the yacc file rules seem a good solution for this problem.
Maybe I misunderstood you?

**Comment by furiel** [comment]
I think you understood correctly. If you can install python to the build machine, then you do not need the workaround I mentioned.

Even though it is often not a difficult to have python on a build system, it is not a hard dependency for syslog-ng, and the code could reflect that. So your ticket is reasonable, and can be resolved by delaying the error reporting till the yacc rules.
