### ISSUE TITLE
riemann: additional default fields

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#257]
`host` and `service` are picked up automatically if not set.
It would be nice to do the same with `state`, `ttl`, `metric` etc.

Some proposals:

* `state` would pickup in this order `${state}`, `${LEVEL}` (or a clever projection thereof to ok,warning,critical)
* `metric` would pickup in this order `${metric}`, `${SEQNUM}`
* `ttl` would pickup in this order `${ttl}`, `$(context-timeout)` or 300 if the latter is 0

The latter seems to me the most interesting: having an event from a correlation context enter riemann, it seems only natural for it to have a TTL equal to its context-timeout length. Only problem being: there is no such template function (or is there?)

**Comment by algernon** [comment]
I was pondering about this just now... it's certainly not terribly hard to add these defaults, but they feel a bit risky. In the sense, that picking up `${state}`, then `${LEVEL}` may be surprising, even if easily overridable with `state("")`. Actually, that's another thing I don't like: `${LEVEL}` is often defined, when the source of the message is syslog, but a good part of my syslog->riemann transformations do not have a state, only metric: I derive the state from the metric on the riemann side, because that has a lot more knowledge about thresholds and all, and the language is more powerful too. To achieve the same effect, I'd have to litter my config with `state("")`, and that's rather ugly.

`host` and `service` are different, those are required fields. `state`, `metric` and `ttl` are optional.

**Comment by faxm0dem** [comment]
:+1:

**Comment by bazsi** [comment]
Is this already resolved? By the reading of it, it seems theres an
agreement, but the code has not yet changed. I'd leave this open until that
happens.

**Comment by algernon** [comment]
The agreement was that the code need not change.

**Comment by bazsi** [comment]
I mixed that up, sorry.
