### ISSUE TITLE
python importing 3rd party libs not working

### ISSUE THREAD

**Issue by chenbekor** [balabit/syslog-ng#2689]
I'm writing a syslog-ng python extension (in an external file rather than embedded) and a basic example works great.

when I try to import some 3rd party lib to my python code (eg- [requests](https://github.com/kennethreitz/requests) ) I'm getting this error:

Error loading Python module; module='example-source', exception='ImportError: No module named \'requests\''

I installed 'requests' using pip install on a Centos 7 machine

p.s - when importing standard packages (like time: 'import time') it works just fine.

am I missing something?

**Comment by furiel** [comment]
Did you compile syslog-ng against python2 or python3? Maybe you need to use pip3 instead of pip.

It is currently a limitation that the python version is decided compile time, and cannot be changed from config. You can query the version with `./syslog-ng --module-registry`, and look for something similar: `[...] The python (python3) module provides Python [...]` (The python version is only included in the printout since 3.18)

<details>

```
Module: mod-python
Status: ok
Version: 3.20.1.279.gf859ff3
Core-Revision: 3.20
Description:
  The python (python3) module provides Python scripted destination support for syslog-ng.
Plugins:
  destination     python
  source          python
  source          python_fetcher
  root            python
  parser          python
  template-func   python
```

</details>

**Comment by chenbekor** [comment]
thanks @furiel that was exactly the issue. problem solved.

**Comment by ssi-anik** [comment]
> The python (python3) module provides Python [...]

Mine is shown `The python (python2) module provides Python scripted destination support for syslog-ng.` from `http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/Debian_8.0`
