### ISSUE TITLE
Support for operation on floats

### ISSUE THREAD

**Issue by smortex** [balabit/syslog-ng#2734]
> We started to talk about the float issue, how to address it.
_Originally posted by @Kokan in https://github.com/balabit/syslog-ng/pull/1710#issuecomment-341640884_

Some logs I am parsing have a duration as `duration=1m1.802729771s`, I though I could capture the minutes (1) and seconds (1.802729771) in two variables, and then `$(+ $(* $(or ${minutes} 0) 60) ${seconds})`, to discover that the operators can only operate on integers.  So I did some dirty workaround, but operators that act on floats may be better (e.g. for adding 2 such duration).

I may be able to allocate some time to add support for this, but before starting anything, I would like to have some feedback because I see multiple ways to reach this goal, the most straightforward being:

* Change the implementation to always manipulate `gdouble` instead of `gint64`;
* Add a new set of operators dedicated to floating point operations (e.g. `$(+. ${a} ${b})`)

Your feedback is appreciated :wink:

**Comment by Kokan** [comment]
I do not recall much of that conversation now :(

I would upgrade the current operations to operate on *float*, but keep the non float behaviour for older configuration, providing some warning about the change.

The main reason as I do not see a configuration/situation where the *float* would not be superior to the *integer*, while the end result can always be rounded (no round support yet, but should be included).

But because the rounding may needed in some cases, I would do this change depend on configuration version and print some warning about the change.

**Comment by smortex** [comment]
Makes sense… maybe we can add a few functions to make the transition smoother, I think about `round`, `ceil` and `floor` on the top of my head…

**Comment by smortex** [comment]
I created #2742 which operates on floats only if the values cannot be parsed as integers.  That way, existing code should keep it's current behavior, and previously unparsable code should now be properly handled.

Operators have been updated so that a float is returned only if at least one of the operands is a float.

I also added `floor`, `ceil` and `round` functions for converting floats to integers.

The idea was to make the behavior to not change with existing code, making it useless to detect the version of the configuration file to choose how to handle numbers.
