### ISSUE TITLE
Is there a complete example/tutorial module of destination driver in c ?

### ISSUE THREAD

**Issue by v-chanikya** [balabit/syslog-ng#2839]
# syslog-ng

## Version of syslog-ng

```
3.22.1
```

## Platform

Docker for development balabit/syslog-ng-ubuntu-xenial

# Issue
I am trying to write a destination driver in syslog-ng in worker thread mode, I followed the documentation dummy module example line to line. It is not up to date and wont work when i tried to compile it in syslog project. 
Can someone update the example in document or help me write one.

**Comment by gaborznagy** [comment]
Hi @v-chanikya!

Thanks for reporting this documentation bug issue.

There is a tutorial for threaded destination drivers on our [gitbook](https://syslog-ng.gitbooks.io/getting-started/content/chapters/chapter_5/section_5.html) page, but you are right, it's a bit outdate:
E.g. 
- the mentioned `LogThrDestDriver` class is renamed to `LogThreadedDestDriver`
- Instead of `#include "logthrdestdrv.h"` use #include "logthrdest/logthrdestdrv.h".

Until the documentation is not updated, I would suggest to check the other threaded dest-drivers in syslog-ng.
I think `amqp`, `smtp` and `stomp` would be good as examples as they are less complex, then `http` for example.

**Comment by v-chanikya** [comment]
Hi @gaborznagy 

Thanks for the help I got the dummy example working.
For future reference, I would like to add location to modules `amqp`, `smtp` and `stomp`, they are  at `modules/afamqp`, `modules/afsmtp`, `modules/afstomp`.
