### ISSUE TITLE
syslog-ng mutlicast destination TTL stuck at 1

### ISSUE THREAD

**Issue by kjhee43** [balabit/syslog-ng#2889]
I am trying to set up a multicast network destination so the logs can be received by multiple hosts without having to send it out X number of times. 

I have:
destination d_multicast { udp(“239.0.0.1” port(4440) ip_ttl(8) ); };

The multicast message goes out, however,  it never reaches the destination because the ttl doesn’t get set to 8. It stays at 1. I can’t get the message off network with a ttl of 1. I’ve tried several different destination setups but none allow the ttl to go over 1.

I tried RHEL7.5 packaged version (3.5.6) and also compiled 3.7.1 and 3.22.1 and all had the same issue? Is there any version that this works in?  Conf file and capture attached. 

![TTL](https://user-images.githubusercontent.com/47122186/63697832-a6220480-c7eb-11e9-8a8a-51ff320ad84f.PNG)
[conf.txt](https://github.com/balabit/syslog-ng/files/3541542/conf.txt)

**Comment by MrAnno** [comment]
Hello @kjhee43,

Thanks for opening this issue.

Currently, the result of the `ip_ttl()` option is not reported back to the user, so it might fail silently due to various reasons. Could you try starting syslog-ng with the `--no-caps` option, please? If this doesn't help, I'd give it a try under `strace` to check the result of the appropriate `setsockopt()` call.

**Comment by MrAnno** [comment]
The `strace` output is perfect, thanks!

It seems `IP_TTL` is successfully set to 8. It sounds good, but in case of multicast addresses, `IP_MULTICAST_TTL` should be set instead of `IP_TTL`.
This should be done automatically by syslog-ng. We have IP multicast address detection, but something is not OK, because your syslog instance ends up setting the wrong option.

I'll have a deeper look tomorrow.

**Comment by alltilla** [comment]
Hi,
I looked into the issue, and it is possible, that we have a multicast auto-detection issue in the code. I will dig deeper into that.

However, I have found a possible workaround. Please try to set the ip to the `localip()` option also:
```
destination d_multicast {
        udp("239.50.30.1" localip("239.50.30.1") port (3330) ip-ttl(8));
};
```
strace:
```
setsockopt(11, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
setsockopt(11, SOL_IP, IP_MULTICAST_TTL, [8], 4) = 0
setsockopt(11, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
```
wireshark:
![ttl2](https://user-images.githubusercontent.com/45236571/63847527-431ca300-c98e-11e9-9578-1b248927c463.png)

**Comment by kjhee43** [comment]
@alltilla 

Your workaround worked. I tested it and am able to get mcast traffic off-network . Thank you!

**Comment by alltilla** [comment]
I am very glad! :)
I will keep the ticket open, until we make sure, that everything works as expected syslog-ng side. (still not sure if this is a bug or not)

**Comment by MrAnno** [comment]
@kjhee43 

@alltilla addressed this as a bug. Starting from syslog-ng 3.24.1, the `localip()` trick won't be needed.
