### ISSUE TITLE
syslog-ng 3.6.1 and journald without journal files.

### ISSUE THREAD

**Issue by kokoko3k** [balabit/syslog-ng#357]
Since 3.6.1, the system() sources expands in a way that it pulls journal files from journald if systemd is detected on linux systems.
This means that if one has "Storage=none" in /etc/systemd/journald.conf, no system messages could be logged.
I don't know if i can call this a regression, but what worked in the past, doesn't work now.
Workaround is to replace the system() source with unix-dgram("/dev/log") in the configuration file.

But since running systemd does not imply having journal files, i think that blindly use systemd-journal() source as systemd is detected is somehow wrong.

**Comment by mitzkia** [comment]
Hello, 
As I see:
You are using systemd service manager with disabled journald (storage=none in configuration), which is not a default usage of journald. And with the default syslog-ng configuration (which is using systemd-journal() source), (or maybe modified) you want to pulling system messages.

In syslog-ng configuration systemd-journal() source refers to using journald with the default configuration in /etc/systemd/journald.conf as the default system log source. syslog-ng uses journald (not just only "/dev/log") by default because it collects all of the messages from the system.

If you want to use other logsource than journald for receiving system messages (e.g: only /dev/log), you need to manually add that lines to syslog-ng configuration, and you also need to disable systemd-journal() source avoid of log duplication.
Please correct me if I missunderstand you.

**Comment by kokoko3k** [comment]
You are completely right, and i already knew what you just said.
In the first post, I was just saying that before 3.6.1 syslog-ng played well with systemd regardless of systemd-journald configuration.
After 3.6.1, syslog-ng requires users to manually edit syslog-ng configuration if they were not using journal files at all; we know why it happens.
I'm incline to call this a regression from the user point of view.
Probably my use cases don't allow me to fully understand, but why syslog-ng changed in that regard? 
What are the adventages?

Thanks for answering anyway.

**Comment by ihrwein** [comment]
systemd and journald forced a way of handling logs to syslog daemons: we couldn't open /dev/log directly because it's the property of journald itself [1]. The strange thing is, that opening that file worked but is was supposed not to work. We implemented the `systemd-syslog()` source, to receive the logs from journald. According to the systemd developers it was the preferred way to handling logs by syslog daemons, but systemd didn't start syslog-ng enough early during the boot process, so we lost logs.

Then they changed their mind, and disabled  `ForwardToSyslog`... We created a new source driver, called `systemd-journald()`, which didn't suffer from log losing so it became the part of the default `system()` source under systemd.

I couldn't find a method to determine whether the journal is empty or `Storage=none` was applied. I think most users use journald so `systemd-journald()` is reasonable to be the default.

You can use the `systemd-syslog()` source, just turn on `ForwardToSyslog`. I think it will solve your problem, but some logs during the boot won't reach syslog-ng.

[1] http://www.freedesktop.org/wiki/Software/systemd/syslog/

**Comment by ihrwein** [comment]
@kokoko3k: Can we close this issue?

**Comment by kokoko3k** [comment]
Yes, unfortunately i was kinda forced to switch from syslog-ng to journald, so i don't care anymore.
Sorry for not notifying you.

**Comment by ihrwein** [comment]
Then I'm closing this. Thanks!
