### ISSUE TITLE
Too much "Error opening file for writing"

### ISSUE THREAD

**Issue by benoiton** [balabit/syslog-ng#464]
I use 2 outputs: 
* one on local filesystem (/var/log/syslog file, on /var filesystem),
* one on GlusterFS filesystem (mounted on /var/rlog).

It happens the remote filesystem to be disconnect. In such a situation, error messages are appended to /var/log/syslog ("Error opening file for writing; filename='/var/rlog/2015-04-18.messages', error='Transport endpoint is not connected (107)'"). With more than 150 lines each second, /var is rapidly full. The more there are errors, the more it logs. The more it logs, the more there are errors.

Is there a way to tweak the logging of syslog-ng itself?

* threaded() option might limit damages.
* suppress() option would avoid the disk filling, but log analyzing (with ELK) of error messages for other applications would be more difficult (count of each type of error would be wrong).

**Comment by bazsi** [comment]
hmm.. syslog-ng should by default suspend to writing to a destination where
an error happens. this is controlled by time_reopen() as an option. a quick
browse through the source seems to indicate that it should work, although
I'm looking at the latest git master source code.

which version of syslog-ng do you use? the alternative of suspending the
file destination for a minute would solve this problem for you?
Bazsi


-- 
Bazsi

**Comment by benoiton** [comment]
I use v3.5.6. 
time_reopen() is not configured. [Default value](https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-3.5-guides/en/syslog-ng-ose-v3.5-guide-admin/html/reference-options.html#idp63928704) should apply (60s).

**Comment by gregory094** [comment]
Hi,
This phenomenon occurs for syslog-ng file-dest tries to open the destination on every msg queued. In `3.6` we are working on a patch that can solve your problem where `affile_dw_reopen` arms a timer to check the availability of the destination and don't try to open it in in `affile_dw_queue` on every msgs queued. 
I'll link the PR here when it's ready.

**Comment by lbudai** [comment]
Some further information what's going on here:

'Error opening file for writing' is printed by `affile_dw_reopen`.

`affile_dw_reopen` is called directly by 
 * `affile_dw_queue` OR 
 * `affile_dw_init`.

In our case, `affile_dw_queue` is not a good candidate because it calls reopen only after `time_reopen` time elapsed. So we have `affile_dw_init`... that method is called by `affile_dd_open_writer` which is called by `affile_dd_queue`. 

What does this mean?
When a writer is not instantiated (eg.: when file is located on a network file system and the file is not available, or the case describe in #138), for every incoming message syslog-ng will try to instantiate a writer instance which then calls `dw_reopen` (in other words: `dw_reopen` is called independently from `time_reopen`).

**Comment by lbudai** [comment]
@benoiton : could you help testing PR #511 ?

patch is for 3.6 but if you want, I can port it 3.5

**Comment by benoiton** [comment]
I'm sorry I cannot help.
 * Due to too much instabilities of my GlusterFS cluster on Raspberry Pis, I changed my architecture and do not use GlusterFS anymore. (I find glusterfs itself prone to error)
 * I'm not at ease to install libs and compile on Raspberry

Anyway, thanks for this patch.

**Comment by ckujau** [comment]
Ah, this exactly what I've run into last night with Debian's [syslog-ng](https://tracker.debian.org/pkg/syslog-ng) 3.5.6: after a unexpected reboot, syslog-ng was started but some log destinations were located on dm-crypt devices that had not been mounted yet (because nobody was around to type in the key) and thus syslog-ng was flooding its own logs with "Error opening file for writing" messages until ENOSPC :-\

I just hope that [#850743](https://bugs.debian.org/850743 "syslog-ng: tls cert check segfault") (aka #1310) gets fixed in time so that the next Debian release will still have syslog-ng included and I can test if this log destination issue has been fixed.
