### ISSUE TITLE
SNMP trap parser

### ISSUE THREAD

**Issue by algernon** [balabit/syslog-ng#518]
(Originally requested by @faxm0dem on IRC):

```
14:19  *           faxmodem has a new parser requirement
14:20  *           faxmodem waits and see who leaves the room
14:20 <            faxmodem> I need to parse a string with arbitrary key/value pairs
14:23 <            faxmodem> e.g. 'foo = STRING: "blah" bar = INT32: 102 baz = STRING: "this should be easy"'
14:30 <            faxmodem> TBH it's to integrate syslog-ng with snmp traps
```

This is really a reminder for myself, to write this on the train. Should be fairly straightforward.

**Comment by bazsi** [comment]
what application uses this format?


-- 
Bazsi

**Comment by faxm0dem** [comment]
There are plenty of use cases: many applications log something like `key=value,foo=bar` and the `csv-parser` only handles values, with pre-defined keys.
The one application which is mentioned here is the default format used by `snmptrapd` and friends to serialize traps. (I don't think it's worth it to write a binary snmp trap parser. The key=value thing would be enough)

**Comment by bazsi** [comment]
ok, got it :)

The best way to implement this would be an SCL wrapper around the format,
e.g.

block source snmptraps() {
    channel {
        source { program("snmptrapd ..."); };
        parser { ... };
    };
};

so at the end, this would be used as a normal source:

source s_whatever {
    snmptraps();
};

which would emit already parsed messages.

Also, regarding the schema to be used when doing this, we should probably
align with name-value pairs that splunk/ELK uses for traps. That way, the
same visualizization/analytics tools would work. Once this is ready, we
could really integrate it into the syslog-ng release.

HTH,

-- 
Bazsi

**Comment by faxm0dem** [comment]
sounds awesome!

**Comment by algernon** [comment]
Hrm. Format. Yeah, I could do that too. I wrote a parser on the train, that'll do for now. I might give a try to the format + scl stuff on the plane back to Budapest.

**Comment by erempel** [comment]
Even though you can make a parser for this, the results are not easily usable from the patterndb.  In general terms, every message goes through the patterndb to be classified, and then routed to a variety of back ends for action, archive, alert etc. The [tag=value]+ formatted messages do not define an order of the tag/value pairs which makes an order dependent patterndb pattern ineffective. If the tag/value formatted message is parsed into the set of tags and values, then it needs to be reassembled for aptterndb to use it, or the template function to patterndb needs to be used to match on specific tags. In order to use the template function to patterndb, the configuration file needs to be defined with the parsed tag names, but those are unknown at configuration time.

It is almost like we need to have some way to specify multiple templates in the patterndb, and all of them need to match for the pattern to be considered a match.
Normally, the template would be "MESSAGE"

<patterndb version="4" pub_date="2009-09-01">
   <ruleset name="junk" id="RS-e17651c7-42fe-43be-8a9a-cb36d1a25fcd">
      <pattern>snmptrapd</pattern>
      <rules>
         <rule id="e17651c7-42fe-43be-8a9a-cb36d1a25fcd" class="someclass">
            <patterns>
               <pattern template="tag1">value1</pattern>
               <pattern template="tag2">value2</pattern>
            </patterns>
            <tags>
               <tag>matched</tag>
            </tags>
            <examples>
               <example>
                   <test_message program="snmptrapd" template="tag1">value1</test_message>
                   <test_message program="snmptrapd" template="tag2">value2</test_message>
                  <test_values>
                  </test_values>
               </example>
            </examples>
         </rule>
    </ruleset>
</patterndb>
