### ISSUE TITLE
escaping backslash in template function (sanitize)

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#520]
I'm having an issue with the escape char `\` when trying to use an example from the documentation ([¶11.1.7. Template functions of syslog-ng OSE](https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/reference-template-functions.html)). The following code does definitely not work, as it replaces all messages with the empty string:

```
rewrite r_sanitize_json {
    set(
        "$(sanitize -i \ $MESSAGE)",
        value("MESSAGE")
    );
};
```

Another [section of the docs about regexps](https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/regular-expressions.html) suggests doing `"$(sanitize -i \\ $MESSAGE)"` instead, but there is no improvement.

The only way I could get this to work as expected was by using 4 backslashes: `"$(sanitize -i \\\\ $MESSAGE)"`.

**Comment by bazsi** [comment]
Hi,

Note that you enclosed the string into double-quotes which processes
backslash on its own. If use used single quotes (') instead, a pair of
backslashes wouldn't be needed.

-- 
Bazsi

**Comment by faxm0dem** [comment]
1. I tried that too and I still need 4
2. the example in the documentation uses double quotes and -`-i \@`

**Comment by bazsi** [comment]
I have now tried it using only an apostrophe and in that case '$(sanitize
-i \\ $MESSAGE)' was parsed properly as if a single backslash was specified
to -i.

rewrite r_sanitize_json {
    set(
        '$(sanitize -i \\ $MESSAGE)',
        value("MESSAGE")
    );
};

One level that processes backslashes is the string literal parsing in the
lexer (cfg-lex.l), which is only used for double quotes and not for
apostrophes. The other level is the argument parsing for $(sanitize) which
allows backslashes in order to specify a single argument that contains
spaces.

Unfortunately all new levels nested as template functions will add another
layer of backslash escaping. So while \\ is enough for $(sanitize), if I
have a $(echo) as the parameter to sanitize, that would need four:

'$(sanitize -i \\ $(echo \\\\ $MESSAGE))'

And so on:

'$(sanitize -i \\ $(echo \\\\ $(echo \\\\\\\\ $MESSAGE)))'

This produces two backslashes in front of the value before $MESSAGE.

This is unfortunate, backslash escaping is similarly a pain when using bash
scripts.


-- 
Bazsi

**Comment by presidento** [comment]
I think this question was answered by @bazsi two years ago, so I close this issue. If it is still relevant, please, reopen it.
