### ISSUE TITLE
Possibility of BULK INSERT via freetds to sql server

### ISSUE THREAD

**Issue by kolbykinzer** [balabit/syslog-ng#575]
I Have had some issues with bulk inserting to sql server. I believe I have brought it up here before, although i was calling it batch inserting. what I am wanting to achieve is a BULK INSERT into sql server, one insert into the DB but 1000 logs. Is this possible through syslog-ng? is the actual logic for inserting in the afsql.c file? I am pretty sure freetds does support the bulk insert, I am trying to find out why syslog-ng is stopping that from happening. Any help would be greatly appreciated, thank you.

**Comment by deirf** [comment]
Hi,

This feature is problematic because syslog-ng add a new record to database via INSERT sql command  thought lbdbi and libdbi-driver and a sql server specific driver (freetds in case MS-SQL).
Afsql.c is an sql independent implementation and we do NOT want to change it and 
most of supported sql servers `bulk insert` implementation is very different from
`bulk insert` sql command (INSERT, COPY, BULK INSERT,...) to those parameters and so on.

**Comment by kolbykinzer** [comment]
Thank you for the information, that's what I was worried about. Just curious if it was possible. Thank you.
