### ISSUE TITLE
java build: `make install` should not rebuild at every run

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#585]
For some reason `make install` always seems to rebuild at least parts of the java module:

```
# ./autogen.sh
[...]
# ./configure
[...]
# make
[...]
  GEN    syslog-ng/syslog-ng
  CC     syslog-ng-ctl/syslog-ng-ctl.o
  CC     syslog-ng-ctl/control-client.o
  CCLD   syslog-ng-ctl/syslog-ng-ctl
  GEN    java-binaries
  GEN    java-modules
# make install
Makefile:11789: warning: overriding recipe for target 'eclipse'
Makefile:11768: warning: ignoring old recipe for target 'eclipse'
  GEN    java-headers
make --no-print-directory install-recursive
Makefile:11789: warning: overriding recipe for target 'eclipse'
Makefile:11768: warning: ignoring old recipe for target 'eclipse'
Makefile:11789: warning: overriding recipe for target 'eclipse'
Makefile:11768: warning: ignoring old recipe for target 'eclipse'
  GEN    java-headers
  GEN    java-binaries
  GEN    java-modules
[...]
```

**Comment by gregory094** [comment]
If you run 'make install', all the java related things are passed to 'gradle' (build, check, install). The output you see is produced by 'gradle' when it checks and install the files. The "real" output is redirected to a gradle logfile though. This redirection is misleading as the example shows. We should remove it in order to make it visible that gradle is not rebuilding those files but checking and installing them.
Thanks for reporting it!

As far as I know @aneutral has a patch about this...

**Comment by lbudai** [comment]
I've already merged that patch.

Gradle has its own dependency managment solution which is not known by `make` and what we are doing is to delegate every java related build operation (including check-if-something-changed) to gradle. This means that we call gradle even if there are no changes in the java class files because only gradle can check it - but in that case gradle won't rebuild anything.

Other reason to remove that redirection: if you build syslog-ng in travis/drone.io/OBS you cannot access the redirected log files...

**Comment by ihrwein** [comment]
@faxm0dem I'd like to close the solved issues which are assigned to milestone `syslog-ng 3.7.1`. Do you  still consider this as a bug (based on Laci's a Gergo's comments)?

**Comment by faxmodem** [comment]
of course, I'm closing this
