### ISSUE TITLE
Question: $PREFIX/share/tools/

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#587]
I've noticed that the `make install` procedure installs files in `/usr/local/share/tools`, namely the following:

```
lex-rules.am
cfg-grammar.y
merge-grammar.pl
system-expand
```

While `system-expand` has been useful to me in the past, it's not clear to me why the other 3 should be installed on the target.

Moreover, it would probably make sense to give some context to the full path of those files, to make them easily identifiable as belonging to syslog-ng.

**Comment by bazsi** [comment]
merge-grammar.pl is needed by out-of-tree modules. it is only installed
into syslog-ng indepent location if you install from source, otherwise it
can be customized with configure options --sharedstatedir or something like
that, which should be done by distributions.

-- 
Bazsi

**Comment by faxm0dem** [comment]
Indeed. Don't you think it should be installed into *e.g.* `$PREFIX/share/syslog-ng/tools/` from source?

**Comment by algernon** [comment]
Heh. I just now realized it is $PREFIX/**share/tools**! I agree, using the package name in the path (by default) would make much more sense.

**Comment by ihrwein** [comment]
I created a fix, but bazsi convinced me, that this should be done by package maintainers. @czanik, what do you think?

**Comment by algernon** [comment]
I disagree with Bazsi. Package maintainers can - and already do - work this around. But putting syslog-ng specific files into a directory with a very common name sounds wrong. (Directories commonly used by other software for a specific purpose, eg `/usr/bin` are a different case)

Also, what is the downside of putting it elsewhere? It remains to be findable via pkg-config, which was the proper way to locate these files to begin with.

**Comment by ihrwein** [comment]
If I install syslog-ng with `make install` and I set `--prefix` during configure, I get syslog-ng installed under, say, `$HOME/install/syslog-ng`. IMHO there is no additional value if an additional syslog-ng subfolder is created.

**Comment by algernon** [comment]
Yes, but if you install outside of home, which is a more common case, as end-users rarely install to their home, there is much additional value.

If I install into `$HOME/local`, so I can have `$HOME/local/bin` on PATH, there is still additional value.

**Comment by bazsi** [comment]
First of all, my opinion originates from when we had
sysconfdir='${sysconfdir}/syslog-ng' in our configure script. That was
removed at one point and now you have to explicitly tell the configure
script where your configuration is. And this is what happens from our
debian/rules file. (and probably the rpm spec file as well).

If we add a subdirectory to a path from configure.ac/Makefile.am files,
that cannot be removed nor customized.

Anyway, I did my reading http://www.gnu.org/prep/standards/standards.html:

>
> "The definition of ‘datadir’ is the same for all packages, so you should
> install your data in a subdirectory thereof. Most packages install their
> data under $(datadir)/package-name/. "
>


As I translate this, it seems to state, that if a package wants a
subdirectory, it should create this itself. This will result in artifacts
like: /opt/syslog-ng/share/syslog-ng, and the only customizable portion is
the /opt/syslog-ng/share part. There's no way to tell the configure scripts
to omit the package-name from the directory. But I can accept this
restriction. The point here is that we shall not modify the default of
${datadir} or ${datarootdir}, but rather we should use those as base and do
something like:

toolsdir=${datadir}/syslog-ng/tools

This way man and info files remain in the standard man/info locations
(/opt/syslog-ng/share/man), only the scripts/tools will get in a separate
directory.

Also, the term "tools" may not be the best to reflect what we install there.


With all of these said, and the theoretical question out of the way, my
notes wrt the patches:

   - instead of having to maintain the toolsdir variable at two places, why
   don't we set it from the configure script and AC_SUBST it, just as we do
   that with moduledir and pidfiledir?

At the end I cleaned this and other stuff up and came up with this patch.
What do you think? Also available at this branch:

https://github.com/bazsi/syslog-ng/tree/f/configure-dir-cleanup

-- 
Bazsi

**Comment by ihrwein** [comment]
LGTM.

**Comment by bazsi** [comment]
thanks, I'll submit it as a pull request then.

-- 
Bazsi

**Comment by algernon** [comment]
@ihrwein's patch modifies `toolsdir`, too, does not modify `datadir`, so the intent is the same. Moving this stuff to configure is better, thiough, so +1!

**Comment by bazsi** [comment]
submitted as PR #882


-- 
Bazsi

**Comment by bazsi** [comment]
This was closed the referenced pull request
