### ISSUE TITLE
java destination: does not run using openjdk-1.7

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#597]
* openjdk-1.7 fails with `Can't find class; class_name='org/syslog_ng/SyslogNgClassLoader'`
* oracle-1.8 and openjdk-1.8 work fine

moved and adapted from https://github.com/balabit/syslog-ng/issues/588#issuecomment-124552708

**Comment by aneutrals** [comment]
Could you provide some more information about your system? I ask because I'm running openjdk 1.7 on Ubuntu 14.04 and java destinations work fine for me.

My output for java -version:
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-0ubuntu1.14.04.1) 

I'm running syslog-ng with the command: sudo LD_PRELOAD=/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server/libjvm.so /usr/local/sbin/syslog-ng -Fedv

(Tested with the latest version compiled from master)

**Comment by faxm0dem** [comment]
I just tried with latest master on my debian and it seems to work okay.
I think I may have mixed up preload and update-alternatives.
Thanks for looking into this - I'm closing this for now
