### ISSUE TITLE
Network destination queues are not created if DNS resolution fails

### ISSUE THREAD

**Issue by ssshukla** [balabit/syslog-ng#659]
Version: 3.6.4
Platform: Ubuntu 14.04

Output queue for network destinations is created only if hostname resolution succeeds. So if network is down (or not ready e.g. during system boot), resolution fails and no queue is created for network destinations and hence syslog-ng fails to forward messages. 

This issue surfaced when it was observed that syslog-ng is not forwarding kernel bootup messages even though they are logged to /var/log/syslog. This can be reproduced by bringing down the network, restarting syslog-ng and then bringing up the network. Messages logged while the network was down and after syslog-ng restart will not be forwarded to network destinations.

syslog-ng should unconditionally create queues as soon as it reads destinations from configuration files.

**Comment by lbudai** [comment]
Thanks for reporting this issue (especially for the analysis!).

**Comment by lbudai** [comment]
Try to summarize what I found [little bit tired, so maybe it will be a little bit messy, but I think it could help to us for creating a patch]:

The problem here is that when name resolution fails we won't initialize the LogWriter instance
which means that when a message is received then we just drop it (as LogWriter instance is missing from the LogPipe tree... and `log_pipe_forward` drops the message when not found a next LogPipe element ). 
LogWriter instance will be created only after the reopen timer elapsed (by default: 60s).

When we setup the LogWriter instance for the afsocket dest, we need the persist name.
Persist name uses some information which is set during the network address setup... but that function fails when network is down... so the fix should solve this issue.

On tomorrow we will send a PR which address this problem.

**Comment by lbudai** [comment]
I have a patch but before I'd create a PR I want to check something...

**Comment by lbudai** [comment]
pr #664 should solve this
(I tested it on my machine, it worked.)
