### ISSUE TITLE
Meta packages for syslog-ng and syslog-ng incubator

### ISSUE THREAD

**Issue by mitzkia** [balabit/syslog-ng#677]
Now we have only specific module packages (under http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/) for example: 
syslog-ng-mod-amqp - Enhanced system logging daemon (AMQP plugin)
syslog-ng-mod-geoip - Enhanced system logging daemon (GeoIP plugin)
syslog-ng-mod-json - Enhanced system logging daemon (JSON plugin)
syslog-ng-mod-mongodb - Enhanced system logging daemon (MongoDB plugin)
syslog-ng-mod-redis - Enhanced system logging daemon (Redis plugin)
...
To easily install all packages at once it would be good if there were a meta package for this purpose. For example:
syslog-ng-mod-all - for syslog-ng core modules
syslog-ng-incubator-mod-all - for syslog-ng incubator modules

**Comment by faxm0dem** [comment]
:+1:

**Comment by algernon** [comment]
FWIW, the syslog-ng in Debian recommends all the core modules already, and apt defaults to install recommends by default too. So syslog-ng should be covered there. (The reason it recommends and not depends on all the core modules is because syslog-ng used to be a single package, and we didn't want to add a ton of dependencies for existing installs)

I'd suggest doing something similar: have a `syslog-ng-incubator` meta package, that depends on all the incubator modules. No need for the `-mod-all` stuff.

**Comment by mitzkia** [comment]
Thanks. After checking again syslog-ng package it installs all core modules. So for core syslog-ng (apt-get install syslog-ng) it works. But we need such a syslog-ng-incubator package.

**Comment by mitzkia** [comment]
Because for now this issue is about only "create a meta package for syslog-ng incubator" and there is a new issue about that #687, we can close this issue.
