### ISSUE TITLE
Every second config reload kills marking

### ISSUE THREAD

**Issue by u2yg** [balabit/syslog-ng#701]
In the config, I specify obligatory marking.

    destination output { file("messages" mark_freq(1) mark_mode(periodical)); };

A mark is output every second, as desired. However, after forcing a config reload, marking stops:

    killall -HUP syslog-ng

Forcing another config reload fixes marking:

    killall -HUP syslog-ng

Actually I'm not sure whether anything else is broken in such a case, however marking and/or persistence is worth investigating.

**Comment by faxm0dem** [comment]
I've had problems trying to use mark-mode(periodical).
Nothing specific, just for the record

**Comment by u2yg** [comment]
That's good to know. mark_mode(internal); also works fine here.

**Comment by juhaszviktor** [comment]
I think, that I understand the root cause

The problem is that if the reload is fast enough (done in 1sec),
then the mark_timer will be unregistered without resetting the expire time in the log_writer_deinit.

in the log_writer_init the mark_timer will be updated, but it won't be updated, because the new expire time will be the same as the current expire time and the "race condition shield" in the ml_batched_timer_update won't register the timer.

My possible solution is, that in case of deinit we should cancel the mark_timer instead of unregister, because the cancel reset the expire date to 0.
