### ISSUE TITLE
syslog-ng disconnects client when message exceeds log_msg_size

### ISSUE THREAD

**Issue by blakeday** [balabit/syslog-ng#881]
At the moment, syslog-ng disconnects clients that try to send log messages exceeding log_msg_size instead of just gracefully accepting and truncating the message.  I took a quick glance at the code, and it appears to only affect clients using RFC5425 framing.

Here is the relevant code:

 if (self->frame_len > self->super.options->max_msg_size)
{
 msg_error("Incoming frame larger than log_msg_size()",
evt_tag_int("log_msg_size", self->super.options->max_msg_size),
evt_tag_int("frame_length", self->frame_len),
NULL);
 return LPS_ERROR;
}

Here are excerpts from my logs showing the problem:

2016-01-20T11:27:28-05:00 [HOST]     ERR syslog-ng[87462]: - Incoming frame larger than log_msg_size(); log_msg_size='16384', frame_length='76218' [meta sequenceId="6560"]
2016-01-20T11:27:28-05:00 [HOST]  NOTICE syslog-ng[87462]: - Syslog connection closed; fd='26', client='AF_INET(127.0.0.1:52627)', local='AF_INET(127.0.0.1:601)' [meta sequenceId="6561"]

I think syslog-ng should gracefully handle long messages (those exceeding log_msg_size) by accepting and truncating the message. It should, of course, log a warning as well.

**Comment by avdhoot** [comment]
+1 samee issue with syslog-ng 3.8.0alpha0

**Comment by bazsi** [comment]
It would probably make sense to work that way, however the change is far
from trivial, as we size our internal buffer according to the
log-msg-size() setting.

So in order to provide the same performance, we would need to implement
fetching and dropping data on the floor past "frame_len", which is a
completely separate state in the input machine.

I'd recommend to increment log-msg-size() once the error message is
displayed, I doubt I'd have time for implementing this behavior nearterm.

-- 
Bazsi

**Comment by szemere** [comment]
Hello!
 Credits for @mitzkia for founding this old ticket.
 #2644 should fixes this.

Br,
Laci

**Comment by Kokan** [comment]
#2644 is merged.
