### ISSUE TITLE
IPv6 Pattern Parser and trailing colons

### ISSUE THREAD

**Issue by aslothinasuit** [balabit/syslog-ng#931]
When using the IPv6 pattern parser in patterndb, I'm seeing an issue with the parser accidentally 'chomping' a trailing colon that is not part of the actual address. For example (modified from [here](https://github.com/balabit/syslog-ng-patterndb/blob/master/applications/openssh/sshd.xml)):

```XML
<?xml version='1.0' encoding='UTF-8'?>
<patterndb version="3" pub_date="2010-04-15">
 <ruleset id='97c1454e-9a1f-4b2b-b272-49b170884863' name='sshd'>
  <pattern>sshd</pattern>
  <rules>
   <rule class='system' id='doesntwork' provider='balabit'>
    <description/>
    <patterns>
     <pattern>Received disconnect from @IPv6:ipv6addr@: @ESTRING:code::@ @ANYSTRING:message@</pattern>
    </patterns>
    <examples>
     <example>
      <test_message program="sshd">Received disconnect from ::ffff:200.200.200.200: 2000: Timeout, server not responding.</test_message>
      <test_values>
       <test_value name="ipv6addr">::ffff:200.200.200.200</test_value>
       <test_value name="code">2000</test_value>
       <test_value name="message">Timeout, server not responding.</test_value>
      </test_values>
     </example>
    </examples>
   </rule>
   <rule class='system' id='totallyworks' provider='balabit'>
    <description/>
    <patterns>
     <pattern>Received disconnect from @IPv6:ipv6addr@ @ESTRING:code::@ @ANYSTRING:message@</pattern>
    </patterns>
    <examples>
     <example>
      <test_message program="sshd">Received disconnect from ::ffff:200.200.200.200 2000: Timeout, server not responding.</test_message>
      <test_values>
       <test_value name="ipv6addr">::ffff:200.200.200.200</test_value>
       <test_value name="code">2000</test_value>
       <test_value name="message">Timeout, server not responding.</test_value>
      </test_values>
     </example>
    </examples>
   </rule>
  </rules>
 </ruleset>
</patterndb>

```

The IP seems valid to me according to [RFC 4291](http://tools.ietf.org/html/rfc4291#page-4) (Section 3, compressed form).

From a quick glance, it looks like there may have been an attempt to prevent this condition [here](https://github.com/balabit/syslog-ng/blob/ee1d0d7f0720c3ded0d2bfaf22ca6e42d669b7a6/modules/dbparser/radix.c#L219) in radix.c, though I can't be sure given I haven't actually stepped through syslog-ng with a debugger and debugging symbols turned on.

This version of syslog-ng is compiled from source into an RPM (with no modifications I know of) and running on CentOS 7.2.1511 (x86_64). The version output is as follows:
```
syslog-ng 3.7.2
Installer-Version: 3.7.2
Revision:
Compile-Date: Dec 17 2015 08:23:32
Available-Modules: affile,afprog,afsocket,afstomp,afuser,basicfuncs,confgen,cryptofuncs,csvparser,dbparser,linux-kmsg-format,syslogformat,system-source,afamqp,graphite,json-plugin,kvformat,pseudofile,sdjournal
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: off
```

Is this expected behavior, a bug or am I misunderstanding something fundamental?

**Comment by bkil-syslogng** [comment]
Thank you for your detailed bug report and thorough investigation. We will look into how to improve parsing in such a situation, though the colon can make parsing difficult in many cases. Given your hint, I could easily reproduce the reported issue by extending the relevant unit tests in `modules/dbparser/tests/test_radix.c:test_matches()`.
```
  test_search_matches(root, "bbb6 ::0: huhuhu",
                      "ipv6", "::0", NULL);

  test_search_matches(root, "bbb6 ::: huhuhu",
                      "ipv6", "::", NULL);

  test_search_matches(root, "bbb6 0:0:0:0:0:0:0:0: huhuhu",
                      "ipv6", "0:0:0:0:0:0:0:0", NULL);

  test_search_matches(root, "bbb6 ::129.144.52.38: huhuhu",
                      "ipv6", "::129.144.52.38", NULL);

  test_search_matches(root, "bbb6 ::ffff:129.144.52.38: huhuhu",
                      "ipv6", "::ffff:129.144.52.38", NULL);
```
and then running `make check`. I guess you could add a few more tests there.

Although, now that you can be sure that what you see is indeed undesired behavior and because you have narrowed down the issue so well, you can even propose a fix in the form of a pull request if you wish. As per the [contributing guide](https://github.com/balabit/syslog-ng/blob/master/CONTRIBUTING.md#patches), you basically just need to:
* click the `Fork` button at the top,
* create a new branch in your fork,
* `git clone` that out,
* [compile it](https://github.com/balabit/syslog-ng/blob/master/.travis.yml#L11),
* experiment with your proposed fix (and some extra tests that cover it),
* push back the changes,
* and finally click `new pull request` at your GitHub fork.

We can guide you at any point of the process if you need help. Thanks again for your cooperation.
