### ISSUE TITLE
LIBTOOL ERROR

### ISSUE THREAD

**Issue by Amey-Jain** [balabit/syslog-ng#932]
I corrected the ./configure error. I was building with make command. But an error occurred again with a version mismatch error of libtool. I ran 'make' after ./autogen.sh and ./configure with the options given in file ".travis.yml" file. Then I ran make command which gave me this output with error..

Making all in src
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -D_GNU_SOURCE -I../src/include -I../src/include   -Werror -Wall -pthread -MT iv_avl.lo -MD -MP -MF .deps/iv_avl.Tpo -c -o iv_avl.lo iv_avl.c
libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from libtool 2.4.2.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
make[5]: **\* [iv_avl.lo] Error 63
make[4]: **\* [all-recursive] Error 1
make[3]: **\* [all] Error 2
make[2]: **\* [lib/ivykis/src/libivykis.la] Error 2
make[1]: **\* [all-recursive] Error 1
make: **\* [all] Error 2
**full ouput**
[make-output.txt](https://github.com/balabit/syslog-ng/files/129683/make-output.txt)

I searched the web but I can't find a working solution. I also tried to run autoreconf and make clean but nothing happened. I know the error is there something with aclocal and configure.ac file but I don't know what to do with them

**Comment by ihrwein** [comment]
I don't know how to solve this, but maybe I can give you a workaround.

If you build for a Linux which supports package management, you can install the ivykis binary package. On Debian based systems this is called `libivykis-dev`. After that, you can tell syslog-ng to use ivykis from the system: `configure --with-ivykis=system <your other options come here>`. I hope this helps.

**Comment by bazsi** [comment]
well, libtool is incorporated into the generated configure script based on
the file aclocal.m4 in the lib/ivykis directory. lib/ivykis/aclocal.m4 is
distributed in our source tarball and is coming from libtool 2.4.2, and the
same version is included in the syslog-ng root in the m4 subdirectory.

You probably have 2.4.6 installed locally (pls confirm that), which
partially gets into our build environment. This version mismatch causes the
problem.

I _think_ that the reason is probably that the one in the syslog-ng root is
replaced whereas the one in the ivykis subtree is not. You can check this
by looking at m4/ltversion.m4 and compare it to

$ grep LT_PACKAGE_VER lib/ivykis/aclocal.m4
[m4_if(m4_version_compare(m4_defn([LT_PACKAGE_VERSION]), [$1]), -1,
m4_define([LT_PACKAGE_VERSION], [2.4.2])

If you look at LT_PACKAGE_VERSION in the two files, they should match.

You can fix this by calling libtoolize in the lib/ivykis directory, which
should install the libtool m4 macros in that directory as well.

-- 
Bazsi

**Comment by presidento** [comment]
Close due to inactivity.
