### ISSUE TITLE
Add $(pwuid_to_nam) and $(grgid_to_nam) functions

### ISSUE THREAD

**Issue by lp0** [balabit/syslog-ng#979]
Existing interfaces provide the UID and GID of the process that sent the log message, but this isn't very readable in log files. Template functions are required to convert these ID values to names using getpwnam(3) and getgrnam(3).

**Comment by bazsi** [comment]
That's pretty useful indeed. Thanks for your contribution. Some comments:

* caching: we should probably cache the results, IIRC there's a generic
(but pretty simple) caching mechanism in lib/cache.{c,h}, hopefully that
can be used. This is potentially called for every message, and doing this
without caching would severely limit performance

* naming: I think we should use more intuitive naming, "nam" is pretty much
a result of a bad naming practice of the UNIX API, so we definitely should
avoid that. Also pwuid and grgid are likewise relating to the C struct
members. We should use something that would work for other netdb-like
databases (e.g. hosts, passwd, groups, networks, services, see
nsswitch.conf) I would use something like: resolve-uid-to-user,
resolve-gid-to-group, resolve-ip-to-hostname and so on)

* tests: since this is new code, some tests should definitely be added. I
know it is a little bit difficult to add tests to stuff that uses the
system APIs, but see test_hostname.c or test_host_resolve.c for examples

* portability: getpwnam_r() should be available on most recent systems, but
I guess not everywhere. We should examine the possibility of falling back
to the non-reentrant version, that would be more portable.

* I think including this in basicfuncs module is fine, however we should
create a separate C file for this. "misc" currently does not depend on
anything outside of syslog-ng core, this would introduce dependencies on
the get*nam calls.

Again, this is really useful code and I'd love to see this integrated.


-- 
Bazsi

**Comment by faxm0dem** [comment]
Are you aware of the existence of the [getent](https://github.com/balabit/syslog-ng-incubator/tree/master/modules/getent) incubator module?

**Comment by lp0** [comment]
I'll use the incubator module instead.

**Comment by bazsi** [comment]
Hmmm can we migrate the incubator module over? Does anyone have information
what's keeping it there?

**Comment by faxm0dem** [comment]
it would be awesome to promote the module from the incubator
